**Hyper parameter tuning**

- The parameters or arguments of model can change by user to get the good model performance

- Grid search

- Random search

- Assume that in Decsision tree we have following hyper parameter

    - criterion : {"gini", "entropy", "log_loss"}
        
    - splitter : {"best", "random"}
     
    - max depth : {1,2,3,4,5,6}
        
- By default we have criterion 'gini' is there

- But the model might be performed when criterion is 'entropy' also

- we need to test the combinations by providing different values

- To try the combinations we have two methods

    - Grid search:
        
        - it is a step by step by consider the all combinations
        
        - in criterion: 3,splitter: 2, max depth=6
                
        - The total combinations are : 3x2x6=36
            
    - Random search:
        
        - It will not do all 36 possibile combiantions
        
        - It will select randomly some combinations
        
- Generally we do Grid search 

- By doing this we have term called Cross validation


**Cross validation**:
    
- Cross validation: CV
    
- CV=4 means we devide data randomly into 4 parts

- Out of these 4 parts every time 3 parts consider as train data, 1 parts consider as test data

- P1  P2  P3  P4  are 4 parts of data

- Combination1:  P1 + P2 + P3 are train data  and P4 as test data
    
    - For Combination-1 will try to imporove model performance by doing Hyper parameter tuning
    
    - Assume there 36 comninations are available in DT
    
    - For the Combination1 will do all 36
 
    - so we have 36 hyper parameter comninations for each combination will have one accuracy
 
    - so we have total 36 accuracy values

- Combination2:  P1 + P2 + P4   are train data  and   P3 as test data
    
    - For Combination-2 will try to imporove model performance by doing Hyper parameter tuning
    
    - Assume there 36 comninations are available in DT
    
    - For the Combination-2 will do all 36 

- Combination3:  P1 + P3 + P4  are train data and P2 as test data
    
    - For Combination-3 will try to imporove model performance by doing Hyper parameter tuning
    
    - Assume there 36 comninations are available in DT
    
    - For the Combination-3 will do all 36 

- Combination-4: P2 + P3 + P4  are train data and P1 as test data
    
    - For Combination-4 will try to imporove model performance by doing Hyper parameter tuning
    
    - Assume there 36 comninations are available in DT
    
    - For the Combination-4 will do all 36
    
- Every combination gives 36 accurcy values corresponding each hyper parameter

- will calculate all the average accuracy of combinations individual accuracy w.r.t to each hyper parameter

- so that will get 36 average accuracy values w.r.t each hyper parameter

- Out of these 36 the maximum one is our best accuracy and corresponding hyper parameters are best parameters

In [2]:
import pandas as pd
indexes=[f"h_{i}" for i in range(1,37)]
col1=[f"combination_1_acc_{i}" for i in range(1,37)]
col2=[f"combination_2_acc_{i}" for i in range(1,37)]
col3=[f"combination_3_acc_{i}" for i in range(1,37)]
col4=[f"combination_4_acc_{i}" for i in range(1,37)]
col5=[f"avg_acc_{i}" for i in range(1,37)]
cols=['C1','C2','C3','C4','Avg acc']
pd.DataFrame(zip(col1,col2,col3,col4,col5),index=indexes,
            columns=cols)

,C1,C2,C3,C4,Avg acc
h_1,combination_1_acc_1,combination_2_acc_1,combination_3_acc_1,combination_4_acc_1,avg_acc_1
h_2,combination_1_acc_2,combination_2_acc_2,combination_3_acc_2,combination_4_acc_2,avg_acc_2
h_3,combination_1_acc_3,combination_2_acc_3,combination_3_acc_3,combination_4_acc_3,avg_acc_3
h_4,combination_1_acc_4,combination_2_acc_4,combination_3_acc_4,combination_4_acc_4,avg_acc_4
h_5,combination_1_acc_5,combination_2_acc_5,combination_3_acc_5,combination_4_acc_5,avg_acc_5
h_6,combination_1_acc_6,combination_2_acc_6,combination_3_acc_6,combination_4_acc_6,avg_acc_6
h_7,combination_1_acc_7,combination_2_acc_7,combination_3_acc_7,combination_4_acc_7,avg_acc_7
h_8,combination_1_acc_8,combination_2_acc_8,combination_3_acc_8,combination_4_acc_8,avg_acc_8
h_9,combination_1_acc_9,combination_2_acc_9,combination_3_acc_9,combination_4_acc_9,avg_acc_9
h_10,combination_1_acc_10,combination_2_acc_10,combination_3_acc_10,combination_4_acc_10,avg_acc_10
h_11,combination_1_acc_11,combination_2_acc_11,combination_3_acc_11,combination_4_acc_11,avg_acc_11
h_12,combination_1_acc_12,combination_2_acc_12,combination_3_acc_12,combination_4_acc_12,avg_acc_12
h_13,combination_1_acc_13,combination_2_acc_13,combination_3_acc_13,combination_4_acc_13,avg_acc_13
h_14,combination_1_acc_14,combination_2_acc_14,combination_3_acc_14,combination_4_acc_14,avg_acc_14
h_15,combination_1_acc_15,combination_2_acc_15,combination_3_acc_15,combination_4_acc_15,avg_acc_15
h_16,combination_1_acc_16,combination_2_acc_16,combination_3_acc_16,combination_4_acc_16,avg_acc_16
h_17,combination_1_acc_17,combination_2_acc_17,combination_3_acc_17,combination_4_acc_17,avg_acc_17
h_18,combination_1_acc_18,combination_2_acc_18,combination_3_acc_18,combination_4_acc_18,avg_acc_18
h_19,combination_1_acc_19,combination_2_acc_19,combination_3_acc_19,combination_4_acc_19,avg_acc_19
h_20,combination_1_acc_20,combination_2_acc_20,combination_3_acc_20,combination_4_acc_20,avg_acc_20
h_21,combination_1_acc_21,combination_2_acc_21,combination_3_acc_21,combination_4_acc_21,avg_acc_21
h_22,combination_1_acc_22,combination_2_acc_22,combination_3_acc_22,combination_4_acc_22,avg_acc_22
h_23,combination_1_acc_23,combination_2_acc_23,combination_3_acc_23,combination_4_acc_23,avg_acc_23
h_24,combination_1_acc_24,combination_2_acc_24,combination_3_acc_24,combination_4_acc_24,avg_acc_24
h_25,combination_1_acc_25,combination_2_acc_25,combination_3_acc_25,combination_4_acc_25,avg_acc_25
h_26,combination_1_acc_26,combination_2_acc_26,combination_3_acc_26,combination_4_acc_26,avg_acc_26
h_27,combination_1_acc_27,combination_2_acc_27,combination_3_acc_27,combination_4_acc_27,avg_acc_27
h_28,combination_1_acc_28,combination_2_acc_28,combination_3_acc_28,combination_4_acc_28,avg_acc_28
h_29,combination_1_acc_29,combination_2_acc_29,combination_3_acc_29,combination_4_acc_29,avg_acc_29
h_30,combination_1_acc_30,combination_2_acc_30,combination_3_acc_30,combination_4_acc_30,avg_acc_30
h_31,combination_1_acc_31,combination_2_acc_31,combination_3_acc_31,combination_4_acc_31,avg_acc_31
h_32,combination_1_acc_32,combination_2_acc_32,combination_3_acc_32,combination_4_acc_32,avg_acc_32
h_33,combination_1_acc_33,combination_2_acc_33,combination_3_acc_33,combination_4_acc_33,avg_acc_33
h_34,combination_1_acc_34,combination_2_acc_34,combination_3_acc_34,combination_4_acc_34,avg_acc_34
h_35,combination_1_acc_35,combination_2_acc_35,combination_3_acc_35,combination_4_acc_35,avg_acc_35
h_36,combination_1_acc_36,combination_2_acc_36,combination_3_acc_36,combination_4_acc_36,avg_acc_36

$Step-1$

**Import the packages**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(color_codes=True)             # To get diffent different colors
pd.set_option('display.max_columns', None)  # To display the max columns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV,cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,\
                            precision_score,\
                            recall_score,\
                            f1_score,\
                            classification_report,\
                            roc_auc_score,roc_curve,auc
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay

$Step-2$:
    
**Read the data**

In [6]:
data=pd.read_csv("Preprocessed_data.csv")
data

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Offer,Avg Monthly Long Distance Charges,Multiple Lines,Internet Type,Avg Monthly GB Download,Online Security,Online Backup,Device Protection Plan,Premium Tech Support,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status
0,0,37,1,0,34.827662,-118.999073,2,9,0,42.39,0,0,16,0,1,0,1,1,0,0,1,1,1,1,65.60,593.30,0.00,0,381.51,974.81,1
1,1,46,0,0,34.162515,-118.203869,0,9,0,10.69,1,0,10,0,0,0,0,0,1,1,0,0,0,1,-4.00,542.40,38.33,10,96.21,610.28,1
2,1,50,0,0,33.645672,-117.922613,0,4,5,33.65,0,2,30,0,0,1,0,0,0,0,1,0,1,0,73.90,280.85,0.00,0,134.60,415.45,0
3,1,78,1,0,38.014457,-122.115432,1,13,4,27.82,0,2,4,0,1,1,0,1,1,0,1,0,1,0,98.00,1237.85,0.00,0,361.66,1599.51,0
4,0,75,1,0,34.227846,-119.079903,3,3,0,7.38,0,2,11,0,0,0,1,1,0,0,1,0,1,1,83.90,267.40,0.00,0,22.14,289.54,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4830,0,53,0,0,36.807595,-118.901544,0,1,5,42.09,0,2,9,0,0,0,0,0,0,0,1,0,1,1,70.15,70.15,0.00,0,42.09,112.24,0
4831,0,20,0,0,32.759327,-116.997260,0,13,4,46.68,0,1,59,1,0,0,1,0,0,1,1,1,0,1,55.15,742.90,0.00,0,606.84,1349.74,1
4832,1,40,1,0,37.734971,-120.954271,1,22,4,16.20,1,2,17,0,0,0,0,0,1,1,1,0,1,0,85.10,1873.70,0.00,0,356.40,2230.10,0
4833,1,22,0,0,39.108252,-123.645121,0,2,5,18.62,0,1,51,0,1,0,0,0,0,0,1,0,1,1,50.30,92.75,0.00,0,37.24,129.99,1
4834,1,21,1,0,33.001813,-117.263628,5,67,1,2.12,0,0,58,1,0,1,1,0,1,1,1,2,0,1,67.85,4627.65,0.00,0,142.04,4769.69,1

In [6]:
# data=pd.read_csv("preprocessd_data_cleaned.csv")
# data

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,weekly_max_night_mins,videos_watched,customer_support_calls,churn
0,0,-0.264643,-0.946659,0,0,-1.508785,0.722258,-0.944404,-1.403000,-0.415473,0
1,0,0.029654,1.235009,0,0,0.304821,-0.901748,-0.688523,-0.599124,0.347522,0
2,0,2.580235,0.658246,0,0,-2.266627,0.613991,-0.483818,-1.403000,2.636507,1
3,0,-1.441834,0.783629,0,1,0.638123,-0.252146,0.079121,-0.197185,1.110517,0
4,0,0.127754,2.288228,0,0,-0.333851,0.253101,-0.893228,1.008630,-0.415473,0
...,...,...,...,...,...,...,...,...,...,...,...
3401,1,-0.805656,0.479710,0,0,0.887802,0.552184,0.865765,-0.495634,-0.415473,1
3402,0,0.477826,0.674425,0,0,2.038061,-0.931071,0.567257,2.100185,0.235227,1
3403,0,-0.550521,0.426099,0,1,-0.410669,0.344847,-0.729485,-0.403904,1.873512,1
3404,0,0.004651,-0.444637,0,0,1.359751,-0.847121,-0.715010,-0.197185,-1.178468,1
3405,0,-0.057028,0.317748,0,0,2.844852,0.098115,-0.550251,0.606692,-1.178468,1

In [10]:
data.columns

Index(['Gender', 'Age', 'Married', 'Number of Dependents', 'Latitude',
       'Longitude', 'Number of Referrals', 'Tenure in Months', 'Offer',
       'Avg Monthly Long Distance Charges', 'Multiple Lines', 'Internet Type',
       'Avg Monthly GB Download', 'Online Security', 'Online Backup',
       'Device Protection Plan', 'Premium Tech Support', 'Streaming TV',
       'Streaming Movies', 'Streaming Music', 'Unlimited Data', 'Contract',
       'Paperless Billing', 'Payment Method', 'Monthly Charge',
       'Total Charges', 'Total Refunds', 'Total Extra Data Charges',
       'Total Long Distance Charges', 'Total Revenue', 'Customer Status'],
      dtype='object')

$Step-3$

**Divide data into input and output**

In [12]:
# Here the target column is Customer Status
X = data.drop('Customer Status', axis=1)
y = data['Customer Status']

$Step-4$:
    
**Train test split**

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=0)
print(X_train.shape),
print(X_test.shape),
print(y_train.shape),
print(y_test.shape)

(3868, 30)
(967, 30)
(3868,)
(967,)

$Step-5$

**Read the base model**

In [16]:
from sklearn.model_selection import GridSearchCV,cross_val_score
from sklearn.tree import DecisionTreeClassifier
base_model_tree=DecisionTreeClassifier()   # Base model
base_model_tree

# we are not fitting the data

DecisionTreeClassifier()

$Step-6$

**Create the parameter file**

In [18]:
base_model_tree.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

**max_depth**:
    
    - The maximum depth of the tree. If None, then nodes are expanded until all leaves are pure or until all leaves contain less        than  min_samples_split samples.
    
**min_samples_split**:
     
      - The minimum number of samples required to split an internal node:
      
**min_samples_leaf**:
    
       - The minimum number of samples required to be at a leaf node.

In [20]:
# You need to create dictonary with hyper parameters
param_grid = {
    "criterion":['gini','entropy'], # 2
    'max_depth': [3, 4, 5, 6, 7, 8], # 6
    'min_samples_split': [2, 3, 4],  # 3
    'min_samples_leaf': [1, 2, 3, 4], # 4
    'random_state': [0, 42] # 2
}


# 2*6*3*4*2=288

$Step-7$

**Apply Grid Search CV**

- we have data

- we have param file

- GridSearchCV : search the each parameter

- **estimator : model name**

In [25]:
# now these parameters to apply in a DT model

grid_search = GridSearchCV(base_model_tree,  # Base model
                           param_grid, # params 
                           scoring='accuracy', # metric
                           cv=5,
                           verbose=True)

# Verbose=True I will show in Deep learning indetail
# Internal operation information will display

In [27]:
grid_search

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, 5, 6, 7, 8],
                         'min_samples_leaf': [1, 2, 3, 4],
                         'min_samples_split': [2, 3, 4],
                         'random_state': [0, 42]},
             scoring='accuracy', verbose=True)

In [20]:
dir(grid_search)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_sk_visual_block_',
 '_validate_data',
 '_validate_params',
 'classes_',
 'cv',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_metadata_routing',
 'get_params',
 'inverse_transform',
 'n_features_in_',
 'n_jobs',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'refit',
 'return_train_score',
 'score',
 'score_samples',
 'scoring',
 'set_params',
 'transform',
 'verbose']

$Step-8$

**Fit the data**

In [29]:
import time
start=time.time()
grid_search.fit(X_train,y_train)  
# Generally we will pass the entire data
# X_train= input data
# y_train= output data
end=time.time()
print("Total time taken is:",(end-start))

Fitting 5 folds for each of 288 candidates, totalling 1440 fits
Total time taken is: 45.27589750289917

E:\Anaconda\Lib\site-packages\numpy\ma\core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,

In [31]:
dir(grid_search)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_sk_visual_block_',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'feature_names_in_',
 'fit',
 'get_metadata_routing',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'refit',
 'refit_time_',
 'return_train_score',
 'score',
 'score_samples',
 'scorer_',
 'scoring',
 'set_params',
 'transform',
 'verbose']

In [24]:
grid_search.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_depth=8, min_samples_leaf=4,
                       random_state=0)

In [62]:
grid_search.cv_results_

{'mean_fit_time': array([0.02429409, 0.01660342, 0.0132576 , 0.01539721, 0.01449718,
        0.01520629, 0.01303968, 0.00983634, 0.00764403, 0.00979567,
        0.00914564, 0.01165342, 0.00731025, 0.009691  , 0.00799665,
        0.00861082, 0.00815072, 0.00871034, 0.00896783, 0.00895624,
        0.00959573, 0.01120505, 0.01156316, 0.01237407, 0.01670551,
        0.01507521, 0.01441031, 0.01107917, 0.01047025, 0.01019754,
        0.01064453, 0.01113462, 0.01161146, 0.01171913, 0.01261721,
        0.0134923 , 0.01360893, 0.01360426, 0.00941424, 0.01313472,
        0.01499653, 0.0133955 , 0.01396971, 0.01349578, 0.01619787,
        0.01434898, 0.0188364 , 0.01484637, 0.02380786, 0.03062596,
        0.02799215, 0.02984347, 0.04735241, 0.02775264, 0.02385607,
        0.02769837, 0.02358971, 0.02175083, 0.02586083, 0.02312732,
        0.02421284, 0.02615929, 0.02436752, 0.02518625, 0.02624607,
        0.02668324, 0.02556014, 0.02457752, 0.02000813, 0.02080288,
        0.02197862, 0.02120209, 0.02072115, 0.02493029, 0.02777152,
        0.02492504, 0.03432765, 0.0333611 , 0.02160258, 0.02777047,
        0.02890191, 0.0239409 , 0.02966499, 0.02913175, 0.0293107 ,
        0.02636805, 0.0247354 , 0.02149982, 0.02400632, 0.02447176,
        0.02279005, 0.02536583, 0.03185043, 0.02642956, 0.02235317,
        0.01958756, 0.01652069, 0.02204986, 0.02488661, 0.02327199,
        0.03042889, 0.02478147, 0.02584581, 0.03114624, 0.02532349,
        0.02912149, 0.02546496, 0.03005199, 0.02106504, 0.02326794,
        0.02250576, 0.02798615, 0.03133249, 0.02823844, 0.02881017,
        0.02704554, 0.02287602, 0.02498975, 0.0280479 , 0.02635832,
        0.03125877, 0.03172364, 0.03076816, 0.02756953, 0.03332191,
        0.0364275 , 0.03124762, 0.03284173, 0.02578864, 0.0325161 ,
        0.02876883, 0.02657094, 0.01597533, 0.02282   , 0.02852988,
        0.03377261, 0.0269289 , 0.03112974, 0.03071852, 0.02924495,
        0.03205433, 0.03363962, 0.03297811, 0.03106709, 0.02268333,
        0.01967206, 0.02042084, 0.02129116, 0.02597589, 0.01888671,
        0.02195501, 0.0216083 , 0.02015467, 0.02330785, 0.01841135,
        0.02221327, 0.02491646, 0.01642876, 0.02289953, 0.02003493,
        0.01847196, 0.02006569, 0.02120137, 0.01917562, 0.02111602,
        0.02291818, 0.02023506, 0.02286396, 0.02838764, 0.02448168,
        0.02719712, 0.02779961, 0.02008824, 0.02718935, 0.02805309,
        0.02369285, 0.02910843, 0.02640252, 0.0300756 , 0.02734442,
        0.02629237, 0.02591033, 0.02393379, 0.02347779, 0.02474117,
        0.02189226, 0.02142076, 0.02665114, 0.02471719, 0.03261333,
        0.03023419, 0.02626576, 0.03041086, 0.03122292, 0.028407  ,
        0.02802162, 0.0260798 , 0.02215142, 0.01950641, 0.02214565,
        0.01818843, 0.0185637 , 0.01622982, 0.01385713, 0.01351175,
        0.01271815, 0.01260452, 0.01549306, 0.01679687, 0.01196036,
        0.01687999, 0.01351371, 0.01086426, 0.01453552, 0.00978999,
        0.00918641, 0.01451116, 0.01329818, 0.01686134, 0.02199187,
        0.02406731, 0.02247529, 0.02147961, 0.02313342, 0.02487183,
        0.02483783, 0.02735   , 0.02626696, 0.02457747, 0.02675319,
        0.02607522, 0.02693286, 0.02739534, 0.02333398, 0.02269025,
        0.0242198 , 0.02119598, 0.0209805 , 0.0207314 , 0.02147079,
        0.02508678, 0.02720833, 0.02733212, 0.02721825, 0.02706294,
        0.03624449, 0.03229752, 0.02858357, 0.02338281, 0.02036085,
        0.02192364, 0.02162175, 0.02543402, 0.02214217, 0.02319589,
        0.02384682, 0.02669811, 0.03252559, 0.02811017, 0.02558289,
        0.02313604, 0.0267724 , 0.03658481, 0.02836514, 0.03024688,
        0.02689705, 0.03137088, 0.0256947 , 0.02691798, 0.02686162,
        0.02706618, 0.02813177, 0.02555208, 0.02497382, 0.03425417,
        0.03074527, 0.03172154, 0.03718891, 0.0302331 , 0.0308147 ,
        0.02056742, 0.02681675, 0.02221737, 0.02371316, 0.02473173,
        0.0189693 , 0.0167038 , 0.01325369]),
 'std_fit_time': array([0.00349943, 0.00288112, 0.00121929, 0.00066299, 0.00247018,
        0.00246897, 0.00356056, 0.00157335, 0.00145405, 0.00172897,
        0.00226048, 0.00094954, 0.00100934, 0.00236934, 0.00137399,
        0.00154346, 0.0006669 , 0.00064289, 0.00181806, 0.00313814,
        0.00125884, 0.00224318, 0.00210474, 0.00175942, 0.00222862,
        0.00195328, 0.00124374, 0.00145872, 0.0011597 , 0.00121772,
        0.00114201, 0.00086419, 0.00121505, 0.00077392, 0.00085232,
        0.00213058, 0.00102707, 0.00104019, 0.00143777, 0.0015983 ,
        0.00420927, 0.00403286, 0.00327603, 0.0038414 , 0.00302791,
        0.00134727, 0.00328389, 0.00383943, 0.00354778, 0.00693789,
        0.01127296, 0.00377645, 0.0423127 , 0.00165437, 0.0059908 ,
        0.00184857, 0.00071538, 0.0067864 , 0.00446518, 0.00499425,
        0.0026793 , 0.00204417, 0.00556784, 0.002591  , 0.00205702,
        0.00964273, 0.00679695, 0.0012577 , 0.00510604, 0.00097119,
        0.00225244, 0.00177718, 0.00534217, 0.00366704, 0.00246403,
        0.00633487, 0.01926121, 0.00475192, 0.00551011, 0.00412214,
        0.0041503 , 0.00691065, 0.00329547, 0.00482494, 0.00672449,
        0.00515922, 0.0026311 , 0.00104127, 0.00315552, 0.00434091,
        0.00219348, 0.00151063, 0.01255375, 0.00349186, 0.00278719,
        0.00269236, 0.00353248, 0.00335543, 0.00240334, 0.00288479,
        0.00227844, 0.00411649, 0.00300135, 0.00404059, 0.00417384,
        0.00373933, 0.00473921, 0.00278782, 0.00129292, 0.00290517,
        0.00349968, 0.00364707, 0.0030924 , 0.01000642, 0.00119631,
        0.00184461, 0.00665575, 0.00304538, 0.00332541, 0.00495772,
        0.00372265, 0.00385691, 0.00125422, 0.00536972, 0.00381989,
        0.00552506, 0.00148497, 0.00111074, 0.00461066, 0.0024486 ,
        0.00304489, 0.00201704, 0.0028216 , 0.00416206, 0.00371655,
        0.00283398, 0.00672693, 0.00342011, 0.00251841, 0.00465317,
        0.00168609, 0.0172471 , 0.0057303 , 0.00437858, 0.00226868,
        0.00121982, 0.0038694 , 0.00282516, 0.00387203, 0.00362896,
        0.00224439, 0.00177161, 0.00379744, 0.00266182, 0.00422331,
        0.00355275, 0.00562688, 0.00519282, 0.0041849 , 0.00307009,
        0.00327618, 0.0039012 , 0.0013945 , 0.00406485, 0.00594341,
        0.00214194, 0.00609552, 0.00321685, 0.00187023, 0.00350227,
        0.0025213 , 0.003768  , 0.00787563, 0.00297218, 0.00308928,
        0.00435499, 0.00313727, 0.00303268, 0.00339284, 0.00334897,
        0.00379237, 0.00317726, 0.0033165 , 0.00121293, 0.00502792,
        0.00389666, 0.00519617, 0.00421011, 0.00776123, 0.0063439 ,
        0.00509068, 0.00172407, 0.0021888 , 0.00260758, 0.00305903,
        0.00415736, 0.00536103, 0.00325969, 0.00278986, 0.00165429,
        0.00100955, 0.00182644, 0.00175519, 0.00184734, 0.0024669 ,
        0.00292874, 0.00310903, 0.00330291, 0.0021896 , 0.00351814,
        0.00415286, 0.00384547, 0.00234442, 0.00407871, 0.00178951,
        0.00034345, 0.00238984, 0.00076928, 0.0008887 , 0.00276655,
        0.00227767, 0.00297717, 0.00410501, 0.00415742, 0.00085052,
        0.00166417, 0.00310108, 0.00235283, 0.00391072, 0.00194134,
        0.00202153, 0.00526097, 0.00323929, 0.00438478, 0.00424709,
        0.00167645, 0.0017579 , 0.00276701, 0.00389236, 0.00318608,
        0.002783  , 0.00385255, 0.00400272, 0.00220253, 0.00561806,
        0.0039662 , 0.00240861, 0.0065556 , 0.00388209, 0.00418649,
        0.00462612, 0.00389847, 0.00209123, 0.00291158, 0.00459557,
        0.00309744, 0.00269266, 0.00355447, 0.00175773, 0.00447676,
        0.00224532, 0.00454026, 0.0124982 , 0.00294253, 0.0025938 ,
        0.00485252, 0.00315991, 0.00155235, 0.00434129, 0.00223147,
        0.00312323, 0.0019762 , 0.00184728, 0.00229217, 0.00591445,
        0.00400062, 0.00259345, 0.00837038, 0.00239267, 0.0061238 ,
        0.00207024, 0.00150041, 0.00197717, 0.00352672, 0.00227994,
        0.00409372, 0.00178572, 0.00144361]),
 'mean_score_time': array([0.00796099, 0.00559673, 0.00375152, 0.00339184, 0.00474658,
        0.00492277, 0.00357528, 0.00224462, 0.00243654, 0.00266871,
        0.00313573, 0.00301771, 0.00233774, 0.00311871, 0.0021842 ,
        0.0020052 , 0.00252066, 0.00242186, 0.00332727, 0.00251541,
        0.00362616, 0.0039669 , 0.00438333, 0.00384851, 0.00402303,
        0.00317845, 0.00299706, 0.00257545, 0.00267835, 0.00160098,
        0.00269804, 0.0024539 , 0.00346503, 0.00309815, 0.002528  ,
        0.00261393, 0.00315156, 0.00309863, 0.00257826, 0.00421677,
        0.0039609 , 0.00313215, 0.00353608, 0.00636544, 0.00360346,
        0.00746121, 0.00555406, 0.00444841, 0.00574965, 0.00841265,
        0.00727878, 0.00757356, 0.00697713, 0.00846586, 0.00450473,
        0.0073709 , 0.00492887, 0.00763645, 0.00657086, 0.00492272,
        0.00873666, 0.00544662, 0.00648866, 0.00419083, 0.00687256,
        0.00542822, 0.00744686, 0.00654616, 0.00560431, 0.00580492,
        0.00545979, 0.0055408 , 0.0055881 , 0.0065599 , 0.00721607,
        0.00486116, 0.00584469, 0.00665035, 0.00735168, 0.00783324,
        0.00574942, 0.00643687, 0.00856695, 0.00754805, 0.00580082,
        0.00573907, 0.00575576, 0.00580111, 0.03548465, 0.00712938,
        0.00492105, 0.00559125, 0.01620574, 0.00497174, 0.00381622,
        0.00310583, 0.00505414, 0.00484796, 0.00433283, 0.00544982,
        0.00504856, 0.00537777, 0.00683937, 0.00629644, 0.00642467,
        0.0046186 , 0.00684476, 0.00520926, 0.00431466, 0.00372391,
        0.00417457, 0.00700631, 0.00655127, 0.00603342, 0.00756884,
        0.0057312 , 0.00502491, 0.0049334 , 0.0062305 , 0.00542293,
        0.00742779, 0.0051405 , 0.00479474, 0.00352654, 0.00733552,
        0.00971274, 0.00621037, 0.00588822, 0.00571604, 0.00560341,
        0.00567522, 0.00524273, 0.00330424, 0.00480919, 0.00486221,
        0.00549293, 0.00805249, 0.00616155, 0.00677996, 0.00500603,
        0.00688868, 0.00706687, 0.00574174, 0.00598669, 0.00685897,
        0.00477471, 0.00588179, 0.00655761, 0.00684323, 0.00719519,
        0.00567145, 0.00574989, 0.00581307, 0.00529385, 0.00578418,
        0.00593696, 0.00681763, 0.00547414, 0.00593615, 0.00490322,
        0.00624266, 0.00554161, 0.00584822, 0.00509758, 0.00697727,
        0.00646124, 0.00663204, 0.00905833, 0.00708017, 0.00451269,
        0.0064682 , 0.00538459, 0.00512953, 0.00925975, 0.00666785,
        0.00719528, 0.00624814, 0.00671921, 0.00583091, 0.00654426,
        0.00555711, 0.0055346 , 0.00516415, 0.00539951, 0.00598474,
        0.00472789, 0.00507913, 0.00603971, 0.00724616, 0.00872731,
        0.00643492, 0.0066184 , 0.00640106, 0.00605488, 0.00800762,
        0.00496774, 0.0061471 , 0.00447478, 0.00466108, 0.00355802,
        0.00331659, 0.00291605, 0.00303917, 0.0024724 , 0.00184584,
        0.00236278, 0.00270247, 0.00255151, 0.0029541 , 0.00188689,
        0.00259781, 0.00264783, 0.00227489, 0.0032865 , 0.00206418,
        0.0017334 , 0.00197377, 0.00269027, 0.00300899, 0.00330849,
        0.00350895, 0.00298405, 0.00334458, 0.00409098, 0.00371108,
        0.00407147, 0.00422096, 0.00382266, 0.00454721, 0.00428071,
        0.00418515, 0.00555396, 0.00398464, 0.00410309, 0.0038414 ,
        0.00388846, 0.0030684 , 0.00310431, 0.00335808, 0.0026382 ,
        0.00367489, 0.00294619, 0.00456791, 0.0042697 , 0.00427518,
        0.00467458, 0.00441318, 0.00386319, 0.00278425, 0.00251117,
        0.00349541, 0.00307684, 0.00280485, 0.00211749, 0.00330443,
        0.00370893, 0.00421252, 0.0044404 , 0.00379577, 0.00382628,
        0.0043035 , 0.00332065, 0.00481396, 0.00452189, 0.00491152,
        0.00437512, 0.00391312, 0.00346217, 0.00369058, 0.00357347,
        0.00429492, 0.00293398, 0.00443015, 0.00400372, 0.00462708,
        0.00462313, 0.00389924, 0.00419745, 0.00437036, 0.00439138,
        0.00251408, 0.00357008, 0.0031116 , 0.00359797, 0.00311904,
        0.00252886, 0.00211697, 0.00241003]),
 'std_score_time': array([0.00158111, 0.00221264, 0.00116195, 0.0010128 , 0.00171399,
        0.00128793, 0.00111862, 0.0002815 , 0.00048678, 0.00071558,
        0.00048023, 0.00030376, 0.00091661, 0.0011149 , 0.00037074,
        0.00057502, 0.00056473, 0.00057833, 0.00102334, 0.0008929 ,
        0.00087592, 0.0007897 , 0.0004739 , 0.00101829, 0.00122453,
        0.00092313, 0.00116941, 0.00044717, 0.00057926, 0.00048968,
        0.00039034, 0.00055341, 0.00063113, 0.00077361, 0.00042864,
        0.00101426, 0.00066461, 0.00082852, 0.00078333, 0.00068562,
        0.00111638, 0.00020076, 0.00120581, 0.00286006, 0.00045376,
        0.00248951, 0.00170414, 0.00180167, 0.00132983, 0.00231303,
        0.00226815, 0.00188284, 0.00149939, 0.0022034 , 0.00093281,
        0.00157091, 0.00247745, 0.0049992 , 0.00089624, 0.00136817,
        0.00172874, 0.00082605, 0.00249724, 0.00083766, 0.0011085 ,
        0.00232576, 0.00241202, 0.0006834 , 0.00198841, 0.00116373,
        0.00136876, 0.00131045, 0.00225231, 0.00170009, 0.00138477,
        0.0019574 , 0.00244856, 0.00206647, 0.00266549, 0.00112338,
        0.0012355 , 0.00275762, 0.0022276 , 0.00218163, 0.00101801,
        0.00159404, 0.00098469, 0.00389562, 0.06117875, 0.00227164,
        0.00072923, 0.00105903, 0.01922924, 0.00224206, 0.00123603,
        0.00102276, 0.00187463, 0.00054142, 0.00095918, 0.00082928,
        0.00142614, 0.00124157, 0.00113953, 0.00124199, 0.00205139,
        0.00128042, 0.00344207, 0.00080189, 0.00144321, 0.00093665,
        0.00124334, 0.00149008, 0.0014177 , 0.00195266, 0.00145095,
        0.00187951, 0.00220706, 0.00120619, 0.00222449, 0.00136956,
        0.0013489 , 0.00125493, 0.00083221, 0.00043715, 0.00319815,
        0.00264457, 0.00148934, 0.00303085, 0.00320483, 0.0019606 ,
        0.0005845 , 0.00162664, 0.00147082, 0.00264606, 0.00085727,
        0.00186995, 0.00398245, 0.0010058 , 0.00172262, 0.00187142,
        0.00164197, 0.00520781, 0.00097419, 0.00107223, 0.0023175 ,
        0.00156248, 0.00247679, 0.00219207, 0.00076045, 0.00205328,
        0.00117826, 0.00143687, 0.00205594, 0.00147922, 0.00331518,
        0.00145862, 0.00374629, 0.00159733, 0.00153855, 0.0008073 ,
        0.0027012 , 0.00216064, 0.00183979, 0.00141747, 0.00218613,
        0.00185913, 0.00176784, 0.0032677 , 0.00152756, 0.00170215,
        0.00130773, 0.00188603, 0.00204212, 0.00331828, 0.00167582,
        0.00284955, 0.00185137, 0.00152271, 0.00144938, 0.00222652,
        0.00233043, 0.00152565, 0.00136732, 0.00194433, 0.00066425,
        0.00208056, 0.00151823, 0.00280324, 0.00295104, 0.00305704,
        0.00225581, 0.00224137, 0.00209924, 0.00138275, 0.00305026,
        0.00138834, 0.00219498, 0.00044642, 0.00098968, 0.00049137,
        0.00074032, 0.0008316 , 0.00060306, 0.00067874, 0.00016261,
        0.00103645, 0.00085452, 0.00103568, 0.00084398, 0.00057251,
        0.00100681, 0.00069427, 0.00090007, 0.00037467, 0.00023293,
        0.00038598, 0.00063241, 0.00038569, 0.00081659, 0.00074189,
        0.00041302, 0.00024763, 0.00048384, 0.00103184, 0.00100601,
        0.0014529 , 0.00031941, 0.00074232, 0.00061902, 0.00078633,
        0.00054376, 0.00230173, 0.0012801 , 0.00062664, 0.00077875,
        0.00107105, 0.00092215, 0.00096126, 0.00049537, 0.00127681,
        0.00141531, 0.00096395, 0.00071347, 0.00082293, 0.00174063,
        0.00077527, 0.00096866, 0.00072311, 0.00116512, 0.00157394,
        0.00136732, 0.00134452, 0.00079398, 0.00081149, 0.00095567,
        0.00092433, 0.00104032, 0.00108112, 0.00082881, 0.00111894,
        0.00099077, 0.00095631, 0.00143926, 0.00056719, 0.00135661,
        0.00212356, 0.00085987, 0.00077112, 0.00076888, 0.00117597,
        0.00104633, 0.00044569, 0.00115524, 0.00090392, 0.00119172,
        0.00131632, 0.00059074, 0.0005275 , 0.00093755, 0.00159761,
        0.00044432, 0.00045175, 0.00076671, 0.00079116, 0.00045238,
        0.00099637, 0.00105041, 0.00049049]),
 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,

In [64]:
grid_search.cv_results_.keys()

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_criterion', 'param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'param_random_state', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'split4_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])

In [66]:
grid_search.cv_results_['params']

[{'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 4,

$Step-9$:
    
**Get the best parameters**

**Estimator means model**

- after developed model 1440 times 

    - 288 paramters comintaions with CV of 5

    - Each paramters combination trained 5 times

    - Ecah parameter combination will get 5 accuracy values

    - Each paramter combination will get one Avg accuracy

    - Like that we will get 288 Avg accuracy values

    - In that One paramter combination has heighest avg accurcay

    - That is best paramter

    - The model is using best parameters called as best estimator

In [68]:
grid_search.best_estimator_

# Estimator means model : 144 models

# best estimator is your model
# if you use this model 
# then we need to find all the metrics

DecisionTreeClassifier(criterion='entropy', max_depth=8, min_samples_leaf=4,
                       random_state=0)

In [70]:
grid_search.best_score_
# not a single accuracy
# avg accuracy of all 5 parts

0.8649001618996222

In [72]:
grid_search.best_params_

{'criterion': 'entropy',
 'max_depth': 8,
 'min_samples_leaf': 4,
 'min_samples_split': 2,
 'random_state': 0}

- Estimator means best Decision Tree model

- best params means the parameters which are used in best model

In [74]:
grid_search.cv_results_

{'mean_fit_time': array([0.02429409, 0.01660342, 0.0132576 , 0.01539721, 0.01449718,
        0.01520629, 0.01303968, 0.00983634, 0.00764403, 0.00979567,
        0.00914564, 0.01165342, 0.00731025, 0.009691  , 0.00799665,
        0.00861082, 0.00815072, 0.00871034, 0.00896783, 0.00895624,
        0.00959573, 0.01120505, 0.01156316, 0.01237407, 0.01670551,
        0.01507521, 0.01441031, 0.01107917, 0.01047025, 0.01019754,
        0.01064453, 0.01113462, 0.01161146, 0.01171913, 0.01261721,
        0.0134923 , 0.01360893, 0.01360426, 0.00941424, 0.01313472,
        0.01499653, 0.0133955 , 0.01396971, 0.01349578, 0.01619787,
        0.01434898, 0.0188364 , 0.01484637, 0.02380786, 0.03062596,
        0.02799215, 0.02984347, 0.04735241, 0.02775264, 0.02385607,
        0.02769837, 0.02358971, 0.02175083, 0.02586083, 0.02312732,
        0.02421284, 0.02615929, 0.02436752, 0.02518625, 0.02624607,
        0.02668324, 0.02556014, 0.02457752, 0.02000813, 0.02080288,
        0.02197862, 0.02120209, 0.02072115, 0.02493029, 0.02777152,
        0.02492504, 0.03432765, 0.0333611 , 0.02160258, 0.02777047,
        0.02890191, 0.0239409 , 0.02966499, 0.02913175, 0.0293107 ,
        0.02636805, 0.0247354 , 0.02149982, 0.02400632, 0.02447176,
        0.02279005, 0.02536583, 0.03185043, 0.02642956, 0.02235317,
        0.01958756, 0.01652069, 0.02204986, 0.02488661, 0.02327199,
        0.03042889, 0.02478147, 0.02584581, 0.03114624, 0.02532349,
        0.02912149, 0.02546496, 0.03005199, 0.02106504, 0.02326794,
        0.02250576, 0.02798615, 0.03133249, 0.02823844, 0.02881017,
        0.02704554, 0.02287602, 0.02498975, 0.0280479 , 0.02635832,
        0.03125877, 0.03172364, 0.03076816, 0.02756953, 0.03332191,
        0.0364275 , 0.03124762, 0.03284173, 0.02578864, 0.0325161 ,
        0.02876883, 0.02657094, 0.01597533, 0.02282   , 0.02852988,
        0.03377261, 0.0269289 , 0.03112974, 0.03071852, 0.02924495,
        0.03205433, 0.03363962, 0.03297811, 0.03106709, 0.02268333,
        0.01967206, 0.02042084, 0.02129116, 0.02597589, 0.01888671,
        0.02195501, 0.0216083 , 0.02015467, 0.02330785, 0.01841135,
        0.02221327, 0.02491646, 0.01642876, 0.02289953, 0.02003493,
        0.01847196, 0.02006569, 0.02120137, 0.01917562, 0.02111602,
        0.02291818, 0.02023506, 0.02286396, 0.02838764, 0.02448168,
        0.02719712, 0.02779961, 0.02008824, 0.02718935, 0.02805309,
        0.02369285, 0.02910843, 0.02640252, 0.0300756 , 0.02734442,
        0.02629237, 0.02591033, 0.02393379, 0.02347779, 0.02474117,
        0.02189226, 0.02142076, 0.02665114, 0.02471719, 0.03261333,
        0.03023419, 0.02626576, 0.03041086, 0.03122292, 0.028407  ,
        0.02802162, 0.0260798 , 0.02215142, 0.01950641, 0.02214565,
        0.01818843, 0.0185637 , 0.01622982, 0.01385713, 0.01351175,
        0.01271815, 0.01260452, 0.01549306, 0.01679687, 0.01196036,
        0.01687999, 0.01351371, 0.01086426, 0.01453552, 0.00978999,
        0.00918641, 0.01451116, 0.01329818, 0.01686134, 0.02199187,
        0.02406731, 0.02247529, 0.02147961, 0.02313342, 0.02487183,
        0.02483783, 0.02735   , 0.02626696, 0.02457747, 0.02675319,
        0.02607522, 0.02693286, 0.02739534, 0.02333398, 0.02269025,
        0.0242198 , 0.02119598, 0.0209805 , 0.0207314 , 0.02147079,
        0.02508678, 0.02720833, 0.02733212, 0.02721825, 0.02706294,
        0.03624449, 0.03229752, 0.02858357, 0.02338281, 0.02036085,
        0.02192364, 0.02162175, 0.02543402, 0.02214217, 0.02319589,
        0.02384682, 0.02669811, 0.03252559, 0.02811017, 0.02558289,
        0.02313604, 0.0267724 , 0.03658481, 0.02836514, 0.03024688,
        0.02689705, 0.03137088, 0.0256947 , 0.02691798, 0.02686162,
        0.02706618, 0.02813177, 0.02555208, 0.02497382, 0.03425417,
        0.03074527, 0.03172154, 0.03718891, 0.0302331 , 0.0308147 ,
        0.02056742, 0.02681675, 0.02221737, 0.02371316, 0.02473173,
        0.0189693 , 0.0167038 , 0.01325369]),
 'std_fit_time': array([0.00349943, 0.00288112, 0.00121929, 0.00066299, 0.00247018,
        0.00246897, 0.00356056, 0.00157335, 0.00145405, 0.00172897,
        0.00226048, 0.00094954, 0.00100934, 0.00236934, 0.00137399,
        0.00154346, 0.0006669 , 0.00064289, 0.00181806, 0.00313814,
        0.00125884, 0.00224318, 0.00210474, 0.00175942, 0.00222862,
        0.00195328, 0.00124374, 0.00145872, 0.0011597 , 0.00121772,
        0.00114201, 0.00086419, 0.00121505, 0.00077392, 0.00085232,
        0.00213058, 0.00102707, 0.00104019, 0.00143777, 0.0015983 ,
        0.00420927, 0.00403286, 0.00327603, 0.0038414 , 0.00302791,
        0.00134727, 0.00328389, 0.00383943, 0.00354778, 0.00693789,
        0.01127296, 0.00377645, 0.0423127 , 0.00165437, 0.0059908 ,
        0.00184857, 0.00071538, 0.0067864 , 0.00446518, 0.00499425,
        0.0026793 , 0.00204417, 0.00556784, 0.002591  , 0.00205702,
        0.00964273, 0.00679695, 0.0012577 , 0.00510604, 0.00097119,
        0.00225244, 0.00177718, 0.00534217, 0.00366704, 0.00246403,
        0.00633487, 0.01926121, 0.00475192, 0.00551011, 0.00412214,
        0.0041503 , 0.00691065, 0.00329547, 0.00482494, 0.00672449,
        0.00515922, 0.0026311 , 0.00104127, 0.00315552, 0.00434091,
        0.00219348, 0.00151063, 0.01255375, 0.00349186, 0.00278719,
        0.00269236, 0.00353248, 0.00335543, 0.00240334, 0.00288479,
        0.00227844, 0.00411649, 0.00300135, 0.00404059, 0.00417384,
        0.00373933, 0.00473921, 0.00278782, 0.00129292, 0.00290517,
        0.00349968, 0.00364707, 0.0030924 , 0.01000642, 0.00119631,
        0.00184461, 0.00665575, 0.00304538, 0.00332541, 0.00495772,
        0.00372265, 0.00385691, 0.00125422, 0.00536972, 0.00381989,
        0.00552506, 0.00148497, 0.00111074, 0.00461066, 0.0024486 ,
        0.00304489, 0.00201704, 0.0028216 , 0.00416206, 0.00371655,
        0.00283398, 0.00672693, 0.00342011, 0.00251841, 0.00465317,
        0.00168609, 0.0172471 , 0.0057303 , 0.00437858, 0.00226868,
        0.00121982, 0.0038694 , 0.00282516, 0.00387203, 0.00362896,
        0.00224439, 0.00177161, 0.00379744, 0.00266182, 0.00422331,
        0.00355275, 0.00562688, 0.00519282, 0.0041849 , 0.00307009,
        0.00327618, 0.0039012 , 0.0013945 , 0.00406485, 0.00594341,
        0.00214194, 0.00609552, 0.00321685, 0.00187023, 0.00350227,
        0.0025213 , 0.003768  , 0.00787563, 0.00297218, 0.00308928,
        0.00435499, 0.00313727, 0.00303268, 0.00339284, 0.00334897,
        0.00379237, 0.00317726, 0.0033165 , 0.00121293, 0.00502792,
        0.00389666, 0.00519617, 0.00421011, 0.00776123, 0.0063439 ,
        0.00509068, 0.00172407, 0.0021888 , 0.00260758, 0.00305903,
        0.00415736, 0.00536103, 0.00325969, 0.00278986, 0.00165429,
        0.00100955, 0.00182644, 0.00175519, 0.00184734, 0.0024669 ,
        0.00292874, 0.00310903, 0.00330291, 0.0021896 , 0.00351814,
        0.00415286, 0.00384547, 0.00234442, 0.00407871, 0.00178951,
        0.00034345, 0.00238984, 0.00076928, 0.0008887 , 0.00276655,
        0.00227767, 0.00297717, 0.00410501, 0.00415742, 0.00085052,
        0.00166417, 0.00310108, 0.00235283, 0.00391072, 0.00194134,
        0.00202153, 0.00526097, 0.00323929, 0.00438478, 0.00424709,
        0.00167645, 0.0017579 , 0.00276701, 0.00389236, 0.00318608,
        0.002783  , 0.00385255, 0.00400272, 0.00220253, 0.00561806,
        0.0039662 , 0.00240861, 0.0065556 , 0.00388209, 0.00418649,
        0.00462612, 0.00389847, 0.00209123, 0.00291158, 0.00459557,
        0.00309744, 0.00269266, 0.00355447, 0.00175773, 0.00447676,
        0.00224532, 0.00454026, 0.0124982 , 0.00294253, 0.0025938 ,
        0.00485252, 0.00315991, 0.00155235, 0.00434129, 0.00223147,
        0.00312323, 0.0019762 , 0.00184728, 0.00229217, 0.00591445,
        0.00400062, 0.00259345, 0.00837038, 0.00239267, 0.0061238 ,
        0.00207024, 0.00150041, 0.00197717, 0.00352672, 0.00227994,
        0.00409372, 0.00178572, 0.00144361]),
 'mean_score_time': array([0.00796099, 0.00559673, 0.00375152, 0.00339184, 0.00474658,
        0.00492277, 0.00357528, 0.00224462, 0.00243654, 0.00266871,
        0.00313573, 0.00301771, 0.00233774, 0.00311871, 0.0021842 ,
        0.0020052 , 0.00252066, 0.00242186, 0.00332727, 0.00251541,
        0.00362616, 0.0039669 , 0.00438333, 0.00384851, 0.00402303,
        0.00317845, 0.00299706, 0.00257545, 0.00267835, 0.00160098,
        0.00269804, 0.0024539 , 0.00346503, 0.00309815, 0.002528  ,
        0.00261393, 0.00315156, 0.00309863, 0.00257826, 0.00421677,
        0.0039609 , 0.00313215, 0.00353608, 0.00636544, 0.00360346,
        0.00746121, 0.00555406, 0.00444841, 0.00574965, 0.00841265,
        0.00727878, 0.00757356, 0.00697713, 0.00846586, 0.00450473,
        0.0073709 , 0.00492887, 0.00763645, 0.00657086, 0.00492272,
        0.00873666, 0.00544662, 0.00648866, 0.00419083, 0.00687256,
        0.00542822, 0.00744686, 0.00654616, 0.00560431, 0.00580492,
        0.00545979, 0.0055408 , 0.0055881 , 0.0065599 , 0.00721607,
        0.00486116, 0.00584469, 0.00665035, 0.00735168, 0.00783324,
        0.00574942, 0.00643687, 0.00856695, 0.00754805, 0.00580082,
        0.00573907, 0.00575576, 0.00580111, 0.03548465, 0.00712938,
        0.00492105, 0.00559125, 0.01620574, 0.00497174, 0.00381622,
        0.00310583, 0.00505414, 0.00484796, 0.00433283, 0.00544982,
        0.00504856, 0.00537777, 0.00683937, 0.00629644, 0.00642467,
        0.0046186 , 0.00684476, 0.00520926, 0.00431466, 0.00372391,
        0.00417457, 0.00700631, 0.00655127, 0.00603342, 0.00756884,
        0.0057312 , 0.00502491, 0.0049334 , 0.0062305 , 0.00542293,
        0.00742779, 0.0051405 , 0.00479474, 0.00352654, 0.00733552,
        0.00971274, 0.00621037, 0.00588822, 0.00571604, 0.00560341,
        0.00567522, 0.00524273, 0.00330424, 0.00480919, 0.00486221,
        0.00549293, 0.00805249, 0.00616155, 0.00677996, 0.00500603,
        0.00688868, 0.00706687, 0.00574174, 0.00598669, 0.00685897,
        0.00477471, 0.00588179, 0.00655761, 0.00684323, 0.00719519,
        0.00567145, 0.00574989, 0.00581307, 0.00529385, 0.00578418,
        0.00593696, 0.00681763, 0.00547414, 0.00593615, 0.00490322,
        0.00624266, 0.00554161, 0.00584822, 0.00509758, 0.00697727,
        0.00646124, 0.00663204, 0.00905833, 0.00708017, 0.00451269,
        0.0064682 , 0.00538459, 0.00512953, 0.00925975, 0.00666785,
        0.00719528, 0.00624814, 0.00671921, 0.00583091, 0.00654426,
        0.00555711, 0.0055346 , 0.00516415, 0.00539951, 0.00598474,
        0.00472789, 0.00507913, 0.00603971, 0.00724616, 0.00872731,
        0.00643492, 0.0066184 , 0.00640106, 0.00605488, 0.00800762,
        0.00496774, 0.0061471 , 0.00447478, 0.00466108, 0.00355802,
        0.00331659, 0.00291605, 0.00303917, 0.0024724 , 0.00184584,
        0.00236278, 0.00270247, 0.00255151, 0.0029541 , 0.00188689,
        0.00259781, 0.00264783, 0.00227489, 0.0032865 , 0.00206418,
        0.0017334 , 0.00197377, 0.00269027, 0.00300899, 0.00330849,
        0.00350895, 0.00298405, 0.00334458, 0.00409098, 0.00371108,
        0.00407147, 0.00422096, 0.00382266, 0.00454721, 0.00428071,
        0.00418515, 0.00555396, 0.00398464, 0.00410309, 0.0038414 ,
        0.00388846, 0.0030684 , 0.00310431, 0.00335808, 0.0026382 ,
        0.00367489, 0.00294619, 0.00456791, 0.0042697 , 0.00427518,
        0.00467458, 0.00441318, 0.00386319, 0.00278425, 0.00251117,
        0.00349541, 0.00307684, 0.00280485, 0.00211749, 0.00330443,
        0.00370893, 0.00421252, 0.0044404 , 0.00379577, 0.00382628,
        0.0043035 , 0.00332065, 0.00481396, 0.00452189, 0.00491152,
        0.00437512, 0.00391312, 0.00346217, 0.00369058, 0.00357347,
        0.00429492, 0.00293398, 0.00443015, 0.00400372, 0.00462708,
        0.00462313, 0.00389924, 0.00419745, 0.00437036, 0.00439138,
        0.00251408, 0.00357008, 0.0031116 , 0.00359797, 0.00311904,
        0.00252886, 0.00211697, 0.00241003]),
 'std_score_time': array([0.00158111, 0.00221264, 0.00116195, 0.0010128 , 0.00171399,
        0.00128793, 0.00111862, 0.0002815 , 0.00048678, 0.00071558,
        0.00048023, 0.00030376, 0.00091661, 0.0011149 , 0.00037074,
        0.00057502, 0.00056473, 0.00057833, 0.00102334, 0.0008929 ,
        0.00087592, 0.0007897 , 0.0004739 , 0.00101829, 0.00122453,
        0.00092313, 0.00116941, 0.00044717, 0.00057926, 0.00048968,
        0.00039034, 0.00055341, 0.00063113, 0.00077361, 0.00042864,
        0.00101426, 0.00066461, 0.00082852, 0.00078333, 0.00068562,
        0.00111638, 0.00020076, 0.00120581, 0.00286006, 0.00045376,
        0.00248951, 0.00170414, 0.00180167, 0.00132983, 0.00231303,
        0.00226815, 0.00188284, 0.00149939, 0.0022034 , 0.00093281,
        0.00157091, 0.00247745, 0.0049992 , 0.00089624, 0.00136817,
        0.00172874, 0.00082605, 0.00249724, 0.00083766, 0.0011085 ,
        0.00232576, 0.00241202, 0.0006834 , 0.00198841, 0.00116373,
        0.00136876, 0.00131045, 0.00225231, 0.00170009, 0.00138477,
        0.0019574 , 0.00244856, 0.00206647, 0.00266549, 0.00112338,
        0.0012355 , 0.00275762, 0.0022276 , 0.00218163, 0.00101801,
        0.00159404, 0.00098469, 0.00389562, 0.06117875, 0.00227164,
        0.00072923, 0.00105903, 0.01922924, 0.00224206, 0.00123603,
        0.00102276, 0.00187463, 0.00054142, 0.00095918, 0.00082928,
        0.00142614, 0.00124157, 0.00113953, 0.00124199, 0.00205139,
        0.00128042, 0.00344207, 0.00080189, 0.00144321, 0.00093665,
        0.00124334, 0.00149008, 0.0014177 , 0.00195266, 0.00145095,
        0.00187951, 0.00220706, 0.00120619, 0.00222449, 0.00136956,
        0.0013489 , 0.00125493, 0.00083221, 0.00043715, 0.00319815,
        0.00264457, 0.00148934, 0.00303085, 0.00320483, 0.0019606 ,
        0.0005845 , 0.00162664, 0.00147082, 0.00264606, 0.00085727,
        0.00186995, 0.00398245, 0.0010058 , 0.00172262, 0.00187142,
        0.00164197, 0.00520781, 0.00097419, 0.00107223, 0.0023175 ,
        0.00156248, 0.00247679, 0.00219207, 0.00076045, 0.00205328,
        0.00117826, 0.00143687, 0.00205594, 0.00147922, 0.00331518,
        0.00145862, 0.00374629, 0.00159733, 0.00153855, 0.0008073 ,
        0.0027012 , 0.00216064, 0.00183979, 0.00141747, 0.00218613,
        0.00185913, 0.00176784, 0.0032677 , 0.00152756, 0.00170215,
        0.00130773, 0.00188603, 0.00204212, 0.00331828, 0.00167582,
        0.00284955, 0.00185137, 0.00152271, 0.00144938, 0.00222652,
        0.00233043, 0.00152565, 0.00136732, 0.00194433, 0.00066425,
        0.00208056, 0.00151823, 0.00280324, 0.00295104, 0.00305704,
        0.00225581, 0.00224137, 0.00209924, 0.00138275, 0.00305026,
        0.00138834, 0.00219498, 0.00044642, 0.00098968, 0.00049137,
        0.00074032, 0.0008316 , 0.00060306, 0.00067874, 0.00016261,
        0.00103645, 0.00085452, 0.00103568, 0.00084398, 0.00057251,
        0.00100681, 0.00069427, 0.00090007, 0.00037467, 0.00023293,
        0.00038598, 0.00063241, 0.00038569, 0.00081659, 0.00074189,
        0.00041302, 0.00024763, 0.00048384, 0.00103184, 0.00100601,
        0.0014529 , 0.00031941, 0.00074232, 0.00061902, 0.00078633,
        0.00054376, 0.00230173, 0.0012801 , 0.00062664, 0.00077875,
        0.00107105, 0.00092215, 0.00096126, 0.00049537, 0.00127681,
        0.00141531, 0.00096395, 0.00071347, 0.00082293, 0.00174063,
        0.00077527, 0.00096866, 0.00072311, 0.00116512, 0.00157394,
        0.00136732, 0.00134452, 0.00079398, 0.00081149, 0.00095567,
        0.00092433, 0.00104032, 0.00108112, 0.00082881, 0.00111894,
        0.00099077, 0.00095631, 0.00143926, 0.00056719, 0.00135661,
        0.00212356, 0.00085987, 0.00077112, 0.00076888, 0.00117597,
        0.00104633, 0.00044569, 0.00115524, 0.00090392, 0.00119172,
        0.00131632, 0.00059074, 0.0005275 , 0.00093755, 0.00159761,
        0.00044432, 0.00045175, 0.00076671, 0.00079116, 0.00045238,
        0.00099637, 0.00105041, 0.00049049]),
 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,

In [34]:
grid_search.cv_results_.keys()
#grid_search.cv_results_['params']

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_criterion', 'param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'param_random_state', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'split4_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])

In [35]:
len(grid_search.cv_results_['param_criterion'].data)

288

In [76]:
grid_search.cv_results_['params']

[{'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 4,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 5,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 6,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 7,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'gini',
  'max_depth': 8,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 2,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 3,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 3,
  'min_samples_leaf': 4,
  'min_samples_split': 4,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 3,
  'random_state': 42},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 4,
  'random_state': 0},
 {'criterion': 'entropy',
  'max_depth': 4,
  'min_samples_leaf': 1,
  'min_samples_split': 4,

In [80]:
grid_search.cv_results_['split0_test_score']
# p0 p1 p2 p3 = train  p5 =test
# 288 params model 288 times developed  288n accuracy

array([0.82752294, 0.82752294, 0.82752294, 0.82752294, 0.82752294,
       0.82752294, 0.82752294, 0.82752294, 0.82752294, 0.82752294,
       0.82752294, 0.82752294, 0.82752294, 0.82752294, 0.82752294,
       0.82752294, 0.82752294, 0.82752294, 0.82752294, 0.82752294,
       0.82752294, 0.82752294, 0.82752294, 0.82752294, 0.82018349,
       0.82018349, 0.82018349, 0.82018349, 0.82018349, 0.82018349,
       0.82018349, 0.82018349, 0.82018349, 0.82018349, 0.82018349,
       0.82018349, 0.82018349, 0.82018349, 0.82018349, 0.82018349,
       0.82018349, 0.82018349, 0.82201835, 0.82201835, 0.82201835,
       0.82201835, 0.82201835, 0.82201835, 0.84587156, 0.84587156,
       0.84587156, 0.84587156, 0.84587156, 0.84587156, 0.84587156,
       0.84587156, 0.84587156, 0.84587156, 0.84587156, 0.84587156,
       0.84587156, 0.84587156, 0.84587156, 0.84587156, 0.84587156,
       0.84587156, 0.84770642, 0.84770642, 0.84770642, 0.84770642,
       0.84770642, 0.84770642, 0.83853211, 0.84220183, 0.83853211,
       0.84220183, 0.83853211, 0.84220183, 0.83669725, 0.84036697,
       0.83669725, 0.84036697, 0.83669725, 0.84036697, 0.83853211,
       0.84036697, 0.83853211, 0.84036697, 0.83853211, 0.84036697,
       0.83669725, 0.83669725, 0.83669725, 0.83669725, 0.83669725,
       0.83669725, 0.8587156 , 0.8587156 , 0.8587156 , 0.8587156 ,
       0.85504587, 0.86422018, 0.85321101, 0.85504587, 0.85321101,
       0.85504587, 0.85321101, 0.85504587, 0.85137615, 0.85321101,
       0.85137615, 0.85321101, 0.85137615, 0.85321101, 0.8587156 ,
       0.85504587, 0.8587156 , 0.85504587, 0.8587156 , 0.85504587,
       0.86788991, 0.86238532, 0.86788991, 0.86238532, 0.8587156 ,
       0.87155963, 0.85321101, 0.86422018, 0.85321101, 0.86422018,
       0.85321101, 0.86422018, 0.85504587, 0.8587156 , 0.85504587,
       0.8587156 , 0.85504587, 0.8587156 , 0.86055046, 0.86422018,
       0.86055046, 0.86422018, 0.86055046, 0.86422018, 0.82752294,
       0.82752294, 0.82752294, 0.82752294, 0.82752294, 0.82752294,
       0.82752294, 0.82752294, 0.82752294, 0.82752294, 0.82752294,
       0.82752294, 0.82752294, 0.82752294, 0.82752294, 0.82752294,
       0.82752294, 0.82752294, 0.82752294, 0.82752294, 0.82752294,
       0.82752294, 0.82752294, 0.82752294, 0.82568807, 0.82568807,
       0.82568807, 0.82568807, 0.82568807, 0.82568807, 0.82568807,
       0.82568807, 0.82568807, 0.82568807, 0.82568807, 0.82568807,
       0.82568807, 0.82568807, 0.82568807, 0.82568807, 0.82568807,
       0.82568807, 0.82568807, 0.82568807, 0.82568807, 0.82568807,
       0.82568807, 0.82568807, 0.85688073, 0.85688073, 0.85688073,
       0.85688073, 0.85688073, 0.85688073, 0.85688073, 0.85688073,
       0.85688073, 0.85688073, 0.85688073, 0.85688073, 0.85688073,
       0.85688073, 0.85688073, 0.85688073, 0.85688073, 0.85688073,
       0.85688073, 0.85688073, 0.85688073, 0.85688073, 0.85688073,
       0.85688073, 0.85321101, 0.84954128, 0.85321101, 0.84954128,
       0.85321101, 0.84954128, 0.85321101, 0.84954128, 0.85321101,
       0.84954128, 0.85321101, 0.84954128, 0.84954128, 0.85137615,
       0.84954128, 0.85137615, 0.84954128, 0.85137615, 0.84770642,
       0.84954128, 0.84770642, 0.84954128, 0.84770642, 0.84954128,
       0.87889908, 0.87889908, 0.87889908, 0.87889908, 0.87522936,
       0.86972477, 0.8733945 , 0.86972477, 0.8733945 , 0.86972477,
       0.8733945 , 0.86972477, 0.86605505, 0.86605505, 0.86605505,
       0.86605505, 0.86605505, 0.86605505, 0.86788991, 0.86605505,
       0.86788991, 0.86605505, 0.86788991, 0.86605505, 0.88807339,
       0.88623853, 0.88807339, 0.88623853, 0.88990826, 0.88440367,
       0.88440367, 0.87889908, 0.88440367, 0.87889908, 0.88440367,
       0.87889908, 0.88073394, 0.88440367, 0.88073394, 0.88440367,
       0.88073394, 0.88440367, 0.88073394, 0.87706422, 0.88073394,
       0.87706422, 0.88073394, 0.87706422])

In [38]:
param1_acc1=grid_search.cv_results_['split0_test_score'][0] # 288
param1_acc2=grid_search.cv_results_['split1_test_score'][0] # 288
param1_acc3=grid_search.cv_results_['split2_test_score'][0] # 288
param1_acc4=grid_search.cv_results_['split3_test_score'][0] # 288
param1_acc5=grid_search.cv_results_['split4_test_score'][0] # 288
print(param1_acc1,param1_acc2,param1_acc3,param1_acc4,param1_acc5)
param1_avg_acc=np.mean([param1_acc1,param1_acc2,param1_acc3,param1_acc4,param1_acc5])
param1_avg_acc
grid_search.cv_results_['mean_test_score'][0]==param1_avg_acc

0.8275229357798165 0.8293577981651377 0.8146788990825689 0.8256880733944955 0.8106617647058824

True

In [39]:
np.max(grid_search.cv_results_['mean_test_score'])

0.8649001618996222

In [40]:
grid_search.best_score_

0.8649001618996222

**np.argmax**

In [42]:
l1=[10,20,30,100,50]
arr1=np.array(l1)
np.max(arr1),np.argmax(arr1)

(100, 3)

In [43]:
idx=np.argmax(grid_search.cv_results_['mean_test_score'])
grid_search.cv_results_['params'][idx]

{'criterion': 'entropy',
 'max_depth': 8,
 'min_samples_leaf': 4,
 'min_samples_split': 2,
 'random_state': 0}

In [44]:
grid_search.best_params_

{'criterion': 'entropy',
 'max_depth': 8,
 'min_samples_leaf': 4,
 'min_samples_split': 2,
 'random_state': 0}

In [84]:
#len(grid_search.cv_results_['split0_test_score'])
c1=grid_search.cv_results_['split0_test_score']
c2=grid_search.cv_results_['split1_test_score']
c3=grid_search.cv_results_['split2_test_score']
c4=grid_search.cv_results_['split3_test_score']
c5=grid_search.cv_results_['split4_test_score']
mean_score=grid_search.cv_results_['mean_test_score']
df=pd.DataFrame(zip(c1,c2,c3,c4,c5,mean_score),
             index=grid_search.cv_results_['params'],
            columns=['C1','C2','C3','C4','C5','mean_test_score'])
avg=[sum(i[:-1])/5 for i in df.values]
print("The maximum avg accuracy is:",max(avg))
df['Average']=avg
df

The maximum avg accuracy is: 0.8649001618996222

,C1,C2,C3,C4,C5,mean_test_score,Average
"{'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2, 'random_state': 0}",0.827523,0.829358,0.814679,0.825688,0.810662,0.821582,0.821582
"{'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2, 'random_state': 42}",0.827523,0.829358,0.814679,0.825688,0.810662,0.821582,0.821582
"{'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 3, 'random_state': 0}",0.827523,0.829358,0.814679,0.825688,0.810662,0.821582,0.821582
"{'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 3, 'random_state': 42}",0.827523,0.829358,0.814679,0.825688,0.810662,0.821582,0.821582
"{'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 4, 'random_state': 0}",0.827523,0.829358,0.814679,0.825688,0.810662,0.821582,0.821582
...,...,...,...,...,...,...,...
"{'criterion': 'entropy', 'max_depth': 8, 'min_samples_leaf': 4, 'min_samples_split': 2, 'random_state': 42}",0.877064,0.871560,0.851376,0.858716,0.845588,0.860861,0.860861
"{'criterion': 'entropy', 'max_depth': 8, 'min_samples_leaf': 4, 'min_samples_split': 3, 'random_state': 0}",0.880734,0.880734,0.849541,0.860550,0.852941,0.864900,0.864900
"{'criterion': 'entropy', 'max_depth': 8, 'min_samples_leaf': 4, 'min_samples_split': 3, 'random_state': 42}",0.877064,0.871560,0.851376,0.858716,0.845588,0.860861,0.860861
"{'criterion': 'entropy', 'max_depth': 8, 'min_samples_leaf': 4, 'min_samples_split': 4, 'random_state': 0}",0.880734,0.880734,0.849541,0.860550,0.852941,0.864900,0.864900
"{'criterion': 'entropy', 'max_depth': 8, 'min_samples_leaf': 4, 'min_samples_split': 4, 'random_state': 42}",0.877064,0.871560,0.851376,0.858716,0.845588,0.860861,0.860861

In [86]:
df[df['Average']==max(df['Average'])].index[0]

{'criterion': 'entropy',
 'max_depth': 8,
 'min_samples_leaf': 4,
 'min_samples_split': 2,
 'random_state': 0}

In [92]:
np.max(df['Average']), np.argmax(df['Average'])

(0.8649001618996222, 282)

In [98]:
grid_search.cv_results_['params'][282]

{'criterion': 'entropy',
 'max_depth': 8,
 'min_samples_leaf': 4,
 'min_samples_split': 2,
 'random_state': 0}

In [94]:
grid_search.best_params_

{'criterion': 'entropy',
 'max_depth': 8,
 'min_samples_leaf': 4,
 'min_samples_split': 2,
 'random_state': 0}

In [106]:
df.iloc[[282]]

,C1,C2,C3,C4,C5,mean_test_score,Average
"{'criterion': 'entropy', 'max_depth': 8, 'min_samples_leaf': 4, 'min_samples_split': 2, 'random_state': 0}",0.880734,0.880734,0.849541,0.86055,0.852941,0.8649,0.8649

In [88]:
df['Average'].max(),grid_search.best_score_

(0.8649001618996222, 0.8649001618996222)

In [48]:
df.values[0][:-1]

array([0.82752294, 0.8293578 , 0.8146789 , 0.82568807, 0.81066176,
       0.82158189])

In [49]:
# Best Parameter
df[['Average']].idxmax().values[0]

{'criterion': 'entropy',
 'max_depth': 8,
 'min_samples_leaf': 4,
 'min_samples_split': 2,
 'random_state': 0}

In [50]:
grid_search.best_params_

{'criterion': 'entropy',
 'max_depth': 8,
 'min_samples_leaf': 4,
 'min_samples_split': 2,
 'random_state': 0}

**Best Estimator means best model**

In [52]:
grid_search.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_depth=8, min_samples_leaf=4,
                       random_state=0)

In [53]:
# id=df[['Average']].idxmax()
# id.values

In [54]:
# df=pd.DataFrame(zip([1,2,3],['A','B','C']),
#                columns=['Col1','Col2'])
# df['Col1'].idxmax() # index=2
# df.take([2])
# df.loc[2]

In [55]:
# # Best accuracy
# df[['Average']].max().values[0]

In [56]:
df[df['Average']==max(df['Average'])]

,C1,C2,C3,C4,C5,mean_test_score,Average
"{'criterion': 'entropy', 'max_depth': 8, 'min_samples_leaf': 4, 'min_samples_split': 2, 'random_state': 0}",0.880734,0.880734,0.849541,0.86055,0.852941,0.8649,0.8649
"{'criterion': 'entropy', 'max_depth': 8, 'min_samples_leaf': 4, 'min_samples_split': 3, 'random_state': 0}",0.880734,0.880734,0.849541,0.86055,0.852941,0.8649,0.8649
"{'criterion': 'entropy', 'max_depth': 8, 'min_samples_leaf': 4, 'min_samples_split': 4, 'random_state': 0}",0.880734,0.880734,0.849541,0.86055,0.852941,0.8649,0.8649

**Cross Validation score**

- Now we use the best model

- Perform the Cross validation score

- Best model means it takes the best parameter

- Cross validation 5 means , it gives 5 accuracy values

- Take the average of all accuracy, again that should be equal to besta accuracy

In [58]:
# Assume that we already know the best model
# best paramters with out doing Grid Search
# Now I want to apply Cross valiation
# In the cross validation every part involved in training and testing
# cross_val_score cv=5 by default

In [ ]:
cross_val_score()

In [108]:
accuracy_list=cross_val_score(grid_search.best_estimator_,
                X_train,
                y_train,
                cv=5,
                scoring='accuracy')
accuracy_list

# It will give each part accuracy
# by using best model (best estimator)

array([0.88073394, 0.88073394, 0.84954128, 0.86055046, 0.85294118])

In [112]:
accuracy_list.mean()

0.8649001618996222

**Model save**

In [117]:
import joblib
path='DT.joblib'
model=grid_search.best_estimator_
joblib.dump(model,path)

['DT.joblib']

In [61]:
## All together

#================================ Step-1: Get the base model===========================================
from sklearn.model_selection import GidSearrchCV,cross_val_score
grid_tree=DecisionTreeClassifier()   # Base model
DT_params=[keys for keys in grid_tree.get_params()]
print("avialable parameters for model:",DT_params)

print("==========================================================================================")

#================================ Step-2: Create a dictionary for params=================================
param_grid = {
    "criterion":['gini','entropy'],
    'max_depth': [3, 4, 5, 6, 7, 8],
    'min_samples_split': [2, 3, 4],
    'min_samples_leaf': [1, 2, 3, 4],
    'random_state': [0, 42]
}

print("Processing parameters are:",param_grid)

print("===============================================================================================")

#============================== Step-3: Apply the Grid serach======================================
grid_search = GridSearchCV(grid_tree,  # Base modl
                           param_grid, # params 
                           scoring='accuracy', # metric
                           cv=5,
                          verbose=True)

#============================= Step-4: fit the model with train data ===============================
grid_search.fit(X_train,y_train)

#============================= Step-5: Get the best parameters=====================================
best_params=grid_search.best_params_
best_score=grid_search.best_score_
print("best params:",best_params)
print("best train accuracy:",best_score)

ImportError: cannot import name 'GidSearrchCV' from 'sklearn.model_selection' (E:\Anaconda\Lib\site-packages\sklearn\model_selection\__init__.py)

**Identify the predictions and Metrics by using best parameters**

- Out of 1440 fittings, one best fit model is outcome

- Best fit means it will give the best parameters

- For me the best parameter combination is

    - entropy
    
    - depth=6
    
    - sample leaf=3
    
    - sampl split=2
    
    - random state=0
    
- Our goal is by using above parameter we need to find the predictions

- And will evaluate model performance

- For that Import Decision Tree and pass the best parameters

- Now fit that model with X_train, y_train

- Get the predictions by passing X_test

- Compare the predictions with y_test

- Calculate

    - Accuracy
    
    - Precision
    
    - Recall
    
    - F1 score
    
    - Roc-Auc curve

In [ ]:
grid_search.best_params_
grid_search.best_estimator_

In [ ]:
from sklearn.tree import DecisionTreeClassifier
# dtree=DecisionTreeClassifier(criterion='entropy',
#                             max_depth=8,
#                             min_samples_leaf=4,
#                             min_samples_split=2,
#                             random_state=0)
# dtree.fit(X_train, y_train)

# # =============================Step-5:  Predictions============================================================

# y_pred_dt=dtree.predict(X_test)
best_model=grid_search.best_estimator_
y_pred_dt=best_model.predict(X_test)
# ============================ Step-6: Metrics==================================================================

acc_dt= round(accuracy_score(y_test,y_pred_dt)*100,2)
f1_dt=round(f1_score(y_test,y_pred_dt),2)
precision_dt=round(precision_score(y_test,y_pred_dt),2)
recall_dt=round(recall_score(y_test,y_pred_dt),2)

print("accuray is:",acc_dt)
print("F1 is:",f1_dt)
print("Precision is:",precision_dt)
print("Recall is:",recall_dt)
print(classification_report(y_test,y_pred_dt))

# ================================Step-7:Confusion matrix=========================================================================

cmt=confusion_matrix(y_test,y_pred_dt)

disp=ConfusionMatrixDisplay(confusion_matrix=cmt,
                            display_labels = [False, True])
disp.plot()
plt.grid(False)
plt.show()


tn, fp, fn, tp = confusion_matrix(y_test,y_pred_dt).ravel()
print("True negative:",tn)
print("False postive:",fp)
print("False negative:",fn)
print("True postive:",tp)

#=======================================Step-8: ROC-AUC curve================================================================

y_dt_pred_prob=best_model.predict_proba(X_test)[:,1]   # Class-1 probabilities
fpr,tpr,threshold=roc_curve(y_test,y_dt_pred_prob) 
plt.plot([0,1],[0,1],color="navy",lw=2,label="Random-Model")
plt.plot(fpr,tpr,color="darkorange",lw=2, label="Decision-Tree Model")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Receiver operating characteristic :ROC-AUC")
plt.legend()
plt.show()
print("Computed Area Under the Curve (AUC)",auc(fpr, tpr))

In [ ]:
# Decision tree will provide imprtant features also
# Information gain values 
dtree.feature_importances_

In [ ]:
imp_df = pd.DataFrame({
    "Feature Name": X_train.columns,
    "Importance": dtree.feature_importances_
})
fi = imp_df.sort_values(by="Importance", ascending=False)
fi

# This concept is valid only for DT
# you can use these features top 10 again develop the model
# Dont use these feature in another model