<h1><center><b>Encoding</b></center></h1>

# EDA 
1. **Data preprocess**
    - missing value analysis
    - Data types mismatch

2. **Data Analysis**
    - Categorical
    - Numerical
    - Bi-variant
    - Multivariant
    - Outlier analysis

3. **Feature Engineering**
    - Impute the outliers
    - ML needs number English to Numbers : Encoding
    - **Scaling :** Standardization and Normaization
    - **Transformation :** Convert into Normal Distribution

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

visa_df=pd.read_csv(r"E:\Python Projects\Data Files\Visadataset.csv")

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [7]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [9]:
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

# Case Status :

In [12]:
# STEP 1 : Find how many unique labels are there
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [14]:
# STEP 2 : Create a dictionary by assigning a values to the labels
#          Follow the alphabetical order
#          Python index start with 0
d={'Certified':0,'Denied':1}
d

{'Certified': 0, 'Denied': 1}

In [20]:
# STEP 3 : Map these dictionary to original values
visa_df['case_status']=visa_df['case_status'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,NaN
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,NaN
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,NaN
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,NaN
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,NaN
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,NaN
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,NaN
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,NaN
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,NaN

In [22]:
visa_df=pd.read_csv(r"E:\Python Projects\Data Files\Visadataset.csv")
visa_df['case_status'].unique()
d={'Certified':0,'Denied':1}
visa_df['case_status']=visa_df['case_status'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [24]:
visa_df=pd.read_csv(r"E:\Python Projects\Data Files\Visadataset.csv")
visa_df['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [28]:
visa_df=pd.read_csv(r"E:\Python Projects\Data Files\Visadataset.csv")
visa_df['continent'].unique()
d={'Asia':0,'Africa':1}

In [ ]:
d={}
d['Asia']=0
d['Africa']=1

In [30]:
labels=visa_df['continent'].unique()
for i in range(len(labels)):
    print(i)

0
1
2
3
4
5

In [32]:
labels=visa_df['continent'].unique()
for i in range(len(labels)):
    print(labels[i],i)

Asia 0
Africa 1
North America 2
Europe 3
South America 4
Oceania 5

In [44]:
labels=visa_df['continent'].unique()
d={}
for i in range(len(labels)):
    d[labels[i]]=i
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [46]:
labels=visa_df['continent'].unique()
d={labels[i]:i for i in range(len(labels))}
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [48]:
visa_df=pd.read_csv(r"E:\Python Projects\Data Files\Visadataset.csv")
labels=visa_df['continent'].unique()
d={labels[i]:i for i in range(len(labels))}
visa_df['continent']=visa_df['continent'].map(d)

In [50]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [52]:
visa_df=pd.read_csv(r"E:\Python Projects\Data Files\Visadataset.csv")
for i in cat[1:]:
    labels=sorted(visa_df[i].unique())
    d={labels[i]:i for i in range(len(labels))}
    visa_df[i]=visa_df[i].map(d)

visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

# sklearn :
 sklearn also known as scikit-learn

 - preprocessing
   - LabelEncoder
  
- **STEP - 1 :** Import the module

- **STEP - 2 :** Save the module

- **STEP - 3 :** Apply fit_transform

    - **fit** means create a **dictionary**
 
    - **Transform** means apply dictionary so that the data will be transformed
 
    - fit means **finding something**
 
    - fit_transform

In [55]:
visa_df=pd.read_csv(r"E:\Python Projects\Data Files\Visadataset.csv")

In [64]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['case_status']=le.fit_transform(visa_df['case_status'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [66]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['continent']=le.fit_transform(visa_df['continent'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [68]:
le.inverse_transform(visa_df['continent'])

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'], dtype=object)

In [70]:
le.inverse_transform(visa_df['continent'])[:5]

array(['Asia', 'Asia', 'Asia', 'Asia', 'Africa'], dtype=object)

In [72]:
visa_df=pd.read_csv(r"E:\Python Projects\Data Files\Visadataset.csv")
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:
    visa_df[i]=le.fit_transform(visa_df[i])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

# OneHot Encoder :

- OneHot means at a time one will be **ON (1)** another will be **OFF(0)**

| case_status | case_status_Denied | case_status_Certified |
|-------------|--------------------|------------------------|
| Denied      | 1                  | 0                      |
| Certified   | 0                  | 1                      |
| Certified   | 0                  | 1                      |
| Denied      | 1                  | 0                      |

In [74]:
visa_df=pd.read_csv(r"E:\Python Projects\Data Files\Visadataset.csv")

In [76]:
pd.get_dummies(visa_df)

,no_of_employees,yr_of_estab,prevailing_wage,case_id_EZYV01,case_id_EZYV02,case_id_EZYV03,case_id_EZYV04,case_id_EZYV05,case_id_EZYV06,case_id_EZYV07,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,14513,2007,592.2029,True,False,False,False,False,False,False,...,False,True,True,False,False,False,False,True,False,True
1,2412,2002,83425.6500,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False
2,44444,2008,122996.8600,False,False,True,False,False,False,False,...,False,True,False,False,False,True,False,True,False,True
3,98,1897,83434.0300,False,False,False,True,False,False,False,...,False,True,False,False,False,True,False,True,False,True
4,1082,2005,149907.3900,False,False,False,False,True,False,False,...,True,False,False,False,False,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,2601,2008,77092.5700,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,True,True,False
25476,3274,2006,279174.7900,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False
25477,1121,1910,146298.8500,False,False,False,False,False,False,False,...,True,False,False,False,False,True,True,False,True,False
25478,1918,1887,86154.7700,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,True,True,False
25479,3195,1960,70876.9100,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False

In [79]:
pd.get_dummies(visa_df,
               columns=cat[1:],
              dtype=int)

,case_id,no_of_employees,yr_of_estab,prevailing_wage,continent_Africa,continent_Asia,continent_Europe,continent_North America,continent_Oceania,continent_South America,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,EZYV01,14513,2007,592.2029,0,1,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
1,EZYV02,2412,2002,83425.6500,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
2,EZYV03,44444,2008,122996.8600,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,EZYV04,98,1897,83434.0300,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,EZYV05,1082,2005,149907.3900,1,0,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,2601,2008,77092.5700,0,1,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,EZYV25477,3274,2006,279174.7900,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
25477,EZYV25478,1121,1910,146298.8500,0,1,0,0,0,0,...,1,0,0,0,0,1,1,0,1,0
25478,EZYV25479,1918,1887,86154.7700,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
25479,EZYV25480,3195,1960,70876.9100,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0

In [ ]:
pd.get_dummies()

Signature:
pd.get_dummies(
    data,
    prefix=None,
    prefix_sep: 'str | Iterable[str] | dict[str, str]' = '_',
    dummy_na: 'bool' = False,
    columns=None,
    sparse: 'bool' = False,
    drop_first: 'bool' = False,
    dtype: 'NpDtype | None' = None,
) -> 'DataFrame'
Docstring:
Convert categorical variable into dummy/indicator variables.

Each variable is converted in as many 0/1 variables as there are different
values. Columns in the output are each named after a value; if the input is
a DataFrame, the name of the original variable is prepended to the value.

Parameters
----------
data : array-like, Series, or DataFrame
    Data of which to get dummy indicators.
prefix : str, list of str, or dict of str, default None
    String to append DataFrame column names.
    Pass a list with length equal to the number of columns
    when calling get_dummies on a DataFrame. Alternatively, `prefix`
    can be a dictionary mapping column names to prefixes.
prefix_sep : str, default '_'
    If appending prefix, separator/delimiter to use. Or pass a
    list or dictionary as with `prefix`.
dummy_na : bool, default False
    Add a column to indicate NaNs, if False NaNs are ignored.
columns : list-like, default None
    Column names in the DataFrame to be encoded.
    If `columns` is None then all the columns with
    `object`, `string`, or `category` dtype will be converted.
sparse : bool, default False
    Whether the dummy-encoded columns should be backed by
    a :class:`SparseArray` (True) or a regular NumPy array (False).
drop_first : bool, default False
    Whether to get k-1 dummies out of k categorical levels by removing the
    first level.
dtype : dtype, default bool
    Data type for new columns. Only a single dtype is allowed.

Returns
-------
DataFrame
    Dummy-coded data. If `data` contains other columns than the
    dummy-coded one(s), these will be prepended, unaltered, to the result.

See Also
--------
Series.str.get_dummies : Convert Series of strings to dummy codes.
:func:`~pandas.from_dummies` : Convert dummy codes to categorical ``DataFrame``.

Notes
-----
Reference :ref:`the user guide <reshaping.dummies>` for more examples.

Examples
--------
>>> s = pd.Series(list('abca'))

>>> pd.get_dummies(s)
       a      b      c
0   True  False  False
1  False   True  False
2  False  False   True
3   True  False  False

>>> s1 = ['a', 'b', np.nan]

>>> pd.get_dummies(s1)
       a      b
0   True  False
1  False   True
2  False  False

>>> pd.get_dummies(s1, dummy_na=True)
       a      b    NaN
0   True  False  False
1  False   True  False
2  False  False   True

>>> df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],
...                    'C': [1, 2, 3]})

>>> pd.get_dummies(df, prefix=['col1', 'col2'])
   C  col1_a  col1_b  col2_a  col2_b  col2_c
0  1    True   False   False    True   False
1  2   False    True    True   False   False
2  3    True   False   False   False    True

>>> pd.get_dummies(pd.Series(list('abcaa')))
       a      b      c
0   True  False  False
1  False   True  False
2  False  False   True
3   True  False  False
4   True  False  False

>>> pd.get_dummies(pd.Series(list('abcaa')), drop_first=True)
       b      c
0  False  False
1   True  False
2  False   True
3  False  False
4  False  False

>>> pd.get_dummies(pd.Series(list('abc')), dtype=float)
     a    b    c
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0
File:      e:\python anaconda\lib\site-packages\pandas\core\reshape\encoding.py
Type:      function

# LabelEncoder vs OneHotEncoder :

- Generally we dont want a relation between **input** columns

- We need both input columns are **NOT correlated** with each other

- We need both input columns are **independent(X,Y)** each other

- We need both input columns are **perpendicular** to each other

- We need both input columns are **Orthogonal** to each other

- We need both input columns are **90 degree phase shift** to each other

- **OneHotEncoder** will achieve above

- But OneHotEncoder creates new columns

  - Columns are increasing means dimensions are increasing
 
  - More dimensions data need more processing time
 
  - More dimensions data need more infra
 
  - This is called **Curse of Dimensionality**