<h1><center><b>Session 5 Numerical Column Analysis</b></center></h1>

In [ ]:
# Import the packages
# Read the data
# Convert cat and numerical columns
# read prevailing_wage data
# wage_data = visa_df[col]
# count = len(wage_data)
# min = np.min
# max = np.max
# mean = np.mean
# median = np.median
# 25p = np.percentile()
# 50p = np.percentile()
# 750

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
visa_df=pd.read_csv(r"E:\Python Projects\Data Files\Visadataset.csv")

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [5]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [7]:
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [10]:
wage_data=visa_df['prevailing_wage']
wage_data

0           592.2029
1         83425.6500
2        122996.8600
3         83434.0300
4        149907.3900
            ...
25475     77092.5700
25476    279174.7900
25477    146298.8500
25478     86154.7700
25479     70876.9100
Name: prevailing_wage, Length: 25480, dtype: float64

In [12]:
# count
count=len(wage_data)
count

25480

In [14]:
# minimum
Min=np.min(wage_data)
Min

2.1367

In [22]:
# maxmum
Min=wage_data.min()
Min

2.1367

In [20]:
# maxmum
Max=np.max(wage_data)
Max

319210.27

In [18]:
# maxmum
Max=wage_data.max()
Max

319210.27

In [24]:
# mean
Mean=np.mean(wage_data)
Mean

74455.81459209183

In [26]:
# mean
Mean=wage_data.mean()
Mean

74455.81459209183

In [28]:
# median
Median=wage_data.median()
Median

70308.20999999999

In [30]:
# median
Median=np.median(wage_data)
Median

70308.20999999999

In [32]:
count=len(wage_data)
Min=round(np.min(wage_data),2)
Max=round(np.max(wage_data),2)
Mean=round(np.mean(wage_data),2)
Median=round(np.median(wage_data),2)

In [38]:
print(np.percentile(wage_data,25))
print(np.quantile(wage_data,25))

34015.479999999996

ValueError: Quantiles must be in the range [0, 1]

In [36]:
print(np.percentile(wage_data,25))
print(np.quantile(wage_data,0.25))

34015.479999999996
34015.479999999996

In [ ]:
count=len(wage_data)
Min=round(np.min(wage_data),2)
Max=round(np.max(wage_data),2)
Mean=round(np.mean(wage_data),2)
Median=round(np.median(wage_data),2)
p_25=round(np.percentile(wage_data,25),2)
p_50=round(np.percentile(wage_data,50),2)
p_75=round(np.percentile(wage_data,75),2)

In [ ]:
count=len(wage_data)
Min=round(np.min(wage_data),2)
p_25=round(np.percentile(wage_data,25),2) # 25 percent
Mean=round(np.mean(wage_data),2)
Median=round(np.median(wage_data),2)
p_50=round(np.percentile(wage_data,50),2) # 50 percent
p_75=round(np.percentile(wage_data,75),2) # 75 percent
Max=round(np.max(wage_data),2)

In [40]:
# Keep all values in a list
# Create a list index = ['count','min','25p','75p']
count=len(wage_data)
Min=round(np.min(wage_data),2)
p_25=round(np.percentile(wage_data,25),2) # 25 percent
Mean=round(np.mean(wage_data),2)
Median=round(np.median(wage_data),2)
p_50=round(np.percentile(wage_data,50),2) # 50 percent
p_75=round(np.percentile(wage_data,75),2) # 75 percent
Max=round(np.max(wage_data),2)
values=[count,Min,p_25,Mean,Median,p_50,p_75,Max]
ids=['count','Min','p_25','Mean','Median','p_50','p_75','Max']
pd.DataFrame(values,index=ids,columns=['prevailing_wage'])

        prevailing_wage
count          25480.00
Min                2.14
p_25           34015.48
Mean           74455.81
Median         70308.21
p_50           70308.21
p_75          107735.51
Max           319210.27

In [44]:
l=[]
for i in range(3):
    a='hello'
    l1=[a]
    l.append(l1)
pd.DataFrame(l)

       0
0  hello
1  hello
2  hello

In [46]:
ids=['count','Min','p_25','Mean','Median','p_50','p_75','Max']
l=[]

for i in num:
    wage_data=visa_df[i]
    count=len(wage_data)
    Min=round(np.min(wage_data),2)
    p_25=round(np.percentile(wage_data,25),2) # 25 percent
    Mean=round(np.mean(wage_data),2)
    Median=round(np.median(wage_data),2)
    p_50=round(np.percentile(wage_data,50),2) # 50 percent
    p_75=round(np.percentile(wage_data,75),2) # 75 percent
    Max=round(np.max(wage_data),2)
    values=[count,Min,p_25,Mean,Median,p_50,p_75,Max]
    l.append(values)

In [48]:
pd.DataFrame(l)

,0,1,2,3,4,5,6,7
0,25480,-26.00,1022.00,5667.04,2109.00,2109.00,3504.00,602069.00
1,25480,1800.00,1976.00,1979.41,1997.00,1997.00,2005.00,2016.00
2,25480,2.14,34015.48,74455.81,70308.21,70308.21,107735.51,319210.27

In [50]:
pd.DataFrame(l,columns=ids,index=num)

,count,Min,p_25,Mean,Median,p_50,p_75,Max
no_of_employees,25480,-26.00,1022.00,5667.04,2109.00,2109.00,3504.00,602069.00
yr_of_estab,25480,1800.00,1976.00,1979.41,1997.00,1997.00,2005.00,2016.00
prevailing_wage,25480,2.14,34015.48,74455.81,70308.21,70308.21,107735.51,319210.27

In [52]:
pd.DataFrame(l,columns=ids,index=num).T # Transpose

        no_of_employees  yr_of_estab  prevailing_wage
count          25480.00     25480.00         25480.00
Min              -26.00      1800.00             2.14
p_25            1022.00      1976.00         34015.48
Mean            5667.04      1979.41         74455.81
Median          2109.00      1997.00         70308.21
p_50            2109.00      1997.00         70308.21
p_75            3504.00      2005.00        107735.51
Max           602069.00      2016.00        319210.27

In [54]:
pd.DataFrame(l,
             columns=ids, # Give index list at columns place
             index=num).T # Transpose, Give numerical values at index place

        no_of_employees  yr_of_estab  prevailing_wage
count          25480.00     25480.00         25480.00
Min              -26.00      1800.00             2.14
p_25            1022.00      1976.00         34015.48
Mean            5667.04      1979.41         74455.81
Median          2109.00      1997.00         70308.21
p_50            2109.00      1997.00         70308.21
p_75            3504.00      2005.00        107735.51
Max           602069.00      2016.00        319210.27

In [58]:
visa_df.describe() # Method

       no_of_employees   yr_of_estab  prevailing_wage
count     25480.000000  25480.000000     25480.000000
mean       5667.043210   1979.409929     74455.814592
std       22877.928848     42.366929     52815.942327
min         -26.000000   1800.000000         2.136700
25%        1022.000000   1976.000000     34015.480000
50%        2109.000000   1997.000000     70308.210000
75%        3504.000000   2005.000000    107735.512500
max      602069.000000   2016.000000    319210.270000