<h1><center><b>Basic DataFrame Operations</b></center></h1>

| **Library**       | **Purpose**                                    |
|-------------------|------------------------------------------------|
| **pandas**        | Used for Database reading, writing, modifying  |
| **numpy**         | Used for Numerical or mathematical operations  |
| **matplotlib**    | Used for plotting                              |
| **seaborn**       | Used for plotting                              |

# EDA : Exploratory Data Analysis

In [ ]:
==============================EDA===================================
1) pandas                         :     Data frame operations
2) numpy                          :     math operations
3) matplotlib                     :     plotting or graphs
4) seaborn                        :     plotting or graphs
5) plotly                         :     plotting or graphs
6) bokhe                          :     plotting or graphs

====================== Machine learning ==========================
7) sickit-learn(sklean)           :     For ALL ML algorithms
8) stats                          :     some statistical operations
    
====================== Deep learning ================================
9) Tensorflow                     :     Deep learning models (Google)
10) keras                         :     Deep learning models tensorflow as backend
11) pytorch                       :     Deep learning models (Meta)
12) opencv                        :     Image and Video opeartions
13) pillow                        :     Image operations

=================== Object Detection models(Transfer learning)==================
14) Mobilenet                     :     Deep learning packages
15) VGGnet                        :     Deep learning packages
16) Resnet                        :     Deep learning packages
17) Inceptionv3                   :     Deep learning packages
18) YOLO                          :     Deep learning packages
    
====================== Natural Language process ===============================
19) NLTK                          :     Natural Langauge Tool Kit
20) SpCy                          :     Alternative to NLTK
21) Wordcloud                     :     Text representation

======================= NLP word Embedding Models ==============================
22) Word2Vec                      :     Google
23) GloVe                         :     Stanford
24) Fasttext                      :     Meta(Face book)

====================== ALLEN NLP (organization) ===========================
25) NLP applications              :     Pyspark as Backend

======================= Optical Character Recognition(OCR) ===============
Extract the text from the image
26) Tesseract
27) easyocr

=========================BERT=======================================
BERT: Bi directional Encoded Representations from Transformers
28) Transformers                  :     Hugging face (Google)

==================== WebScrapping ===========================
29) SQLITE                        :     Connect the Database using python In [ ]: In [ ]:
30) Selenium
31) Beautiful soup
32) Regex

===================== GenAI and LLM =============================
33) Langchain                     :     To Connect all LLM models
34) GPT                           :     OpenAI
35) Gemini                        :     Google
36) Llama                         :     Meta
37) Grok                          :     XAi
38) BedRock                       :     Amazon
39) Claude AI                     :     Anthropic

=================== Agentic AI==================================
40) Langraph
41) CrewAI
42) Phidata
43) Autogen

==================== API creation==============================
44) Flask
45) FastAPI
46) Gradio
47) Django

===================== WebAppliaction ===========================
48) Streamlit

======================= Model deployment(MLops) ==============================
49) mlflow
50) Kubeflow

========================== Cloud AI =========================================
51) Azure Cognitive services
52) Azure ML Studio
53) GCP vertexAI
54) AWS Sagemaker
    
=============================== Extra ========================================
55) random
56) time
57) math
58) logging
59) warnings
60) date

# STEP - 1 : Import required packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# STEP - 2 : Create Dataframe using List

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

    .. versionchanged:: 1.3.0

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
...                    columns=['a', 'b', 'c'])
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
>>> df3 = pd.DataFrame(data, columns=['c', 'a'])
...
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3
File:           e:\python anaconda\lib\site-packages\pandas\core\frame.py
Type:           type
Subclasses:     SubclassedDataFrame

In [22]:
names=['Ramesh','Suresh','Sathish']
# pd.DataFrame(data,index,columns)
pd.DataFrame(names)

         0
0   Ramesh
1   Suresh
2  Sathish

In [20]:
names=['Ramesh','Suresh','Sathish']
pd.DataFrame(data=names)

         0
0   Ramesh
1   Suresh
2  Sathish

# STEP - 3 : Add column

In [ ]:
names=['Ramesh','Suresh','Satish']
pd.DataFrame(names,columns='Names') # ERROR

In [18]:
names=['Ramesh','Suresh','Sathish']
pd.DataFrame(names,columns=['Names']) # Provide a list

     Names
0   Ramesh
1   Suresh
2  Sathish

# STEP - 4 : Update the index

In [29]:
names=['Ramesh','Suresh','Sathish']
pd.DataFrame(names,index=['A'])

ValueError: Shape of passed values is (3, 1), indices imply (1, 1)

In [31]:
names=['Ramesh','Suresh','Sathish']
pd.DataFrame(names,index=['A','B','C'])

         0
A   Ramesh
B   Suresh
C  Sathish

In [33]:
names=['Ramesh','Suresh','Sathish']
cols=['Names']
idx=['A','B','C']
pd.DataFrame(names,index=idx,columns=cols)

     Names
A   Ramesh
B   Suresh
C  Sathish

# STEP - 5 : Create a DataFrame with multiple columns

In [49]:
names=['Ramesh','Suresh','Sathish']
city=['Hyd','Bangaluru','Chennai']
data=[names,city]
cols=['Names','City']
idx=['A','B','C']
pd.DataFrame(data)
# index beacame Columns & Columns became index

        0          1        2
0  Ramesh     Suresh  Sathish
1     Hyd  Bangaluru  Chennai

In [45]:
names=['Ramesh','Suresh','Sathish']
city=['Hyd','Bangaluru','Chennai']
data=[names,city]
cols=['Names','City']
idx=['A','B','C']
pd.DataFrame(data).T # T - Transpose

         0          1
0   Ramesh        Hyd
1   Suresh  Bangaluru
2  Sathish    Chennai

In [47]:
names=['Ramesh','Suresh','Sathish']
city=['Hyd','Bangaluru','Chennai']
data=[names,city]
cols=['Names','City']
idx=['A','B','C']
pd.DataFrame(data,index=cols,columns=idx).T

     Names       City
A   Ramesh        Hyd
B   Suresh  Bangaluru
C  Sathish    Chennai

In [51]:
names=['Ramesh','Suresh','Sathish']
city=['Hyd','Bangaluru','Chennai']
data=zip(names,city)

cols=['Names','City']
idx=['A','B','C']
pd.DataFrame(data)

         0          1
0   Ramesh        Hyd
1   Suresh  Bangaluru
2  Sathish    Chennai

In [53]:
names=['Ramesh','Suresh','Sathish']
city=['Hyd','Bangaluru','Chennai']
data=zip(names,city)

cols=['Names','City']
idx=['A','B','C']
pd.DataFrame(data,index=idx,columns=cols)

     Names       City
A   Ramesh        Hyd
B   Suresh  Bangaluru
C  Sathish    Chennai

In [57]:
names=['Ramesh','Suresh','Sathish']
city=['Hyd','Bengaluru','Chennai']
age=['30','28','35']
data=zip(names,city,age)

cols=['Names','City','Age']
idx=['A','B','C']
pd.DataFrame(data,index=idx,columns=cols)

     Names       City Age
A   Ramesh        Hyd  30
B   Suresh  Bengaluru  28
C  Sathish    Chennai  35

# STEP - 6 : How to add data to empty DataFrame

In [61]:
l=[]
l.append(20)
l

[20]

In [63]:
d={}
d['Names']='Ramesh'
d # Dictionary

{'Names': 'Ramesh'}

In [69]:
d={}
d['Names']=['Ramesh','Suresh','Satish']
d # Dictionary

{'Names': ['Ramesh', 'Suresh', 'Satish']}

In [65]:
s=''
s=s+'apple'
s

'apple'

In [67]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [71]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df

    Names
0  Ramesh
1  Suresh
2  Satish

In [73]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df['Age']=[30,28,35]
df['city']=['Hyd','Bengaluru','Chennai']
df

    Names  Age       city
0  Ramesh   30        Hyd
1  Suresh   28  Bengaluru
2  Satish   35    Chennai

# STEP - 7 : Create a DataFrame using dictionary

In [77]:
dict1={'Names':['Ramesh','Suresh','Satish'],
        'Age':[30,28,35],
        'city':['Hyd','Bengaluru','Chennai']}
dict1

{'Names': ['Ramesh', 'Suresh', 'Satish'],
 'Age': [30, 28, 35],
 'city': ['Hyd', 'Bengaluru', 'Chennai']}

In [81]:
dict1={'Names':['Ramesh','Suresh','Satish'],
        'Age':[30,28,35],
        'city':['Hyd','Bengaluru','Chennai']}
df=pd.DataFrame(dict1)
df

    Names  Age       city
0  Ramesh   30        Hyd
1  Suresh   28  Bengaluru
2  Satish   35    Chennai

# STEP - 8 : Methods
- shape

- size

- columns

- dtypes

- isnull

In [85]:
df.shape

(3, 3)

In [87]:
df.size

9

In [89]:
df.columns

Index(['Names', 'Age', 'city'], dtype='object')

In [91]:
df.dtypes

Names    object
Age       int64
city     object
dtype: object

In [93]:
df.isnull

<bound method DataFrame.isnull of     Names  Age       city
0  Ramesh   30        Hyd
1  Suresh   28  Bengaluru
2  Satish   35    Chennai>

In [97]:
df.isnull() # Is null() available , it is NOT available so 'False'

   Names    Age   city
0  False  False  False
1  False  False  False
2  False  False  False

In [101]:
#Columns wise null values NOT available
df.isnull().sum()

Names    0
Age      0
city     0
dtype: int64

# STEP - 9 : Rename the columns

In [105]:
dict1={'Names':['Ramesh','Suresh','Satish'],
        'Age':[30,28,35],
        'city':['Hyd','Bengaluru','Chennai']}
df=pd.DataFrame(dict1)
df

    Names  Age       city
0  Ramesh   30        Hyd
1  Suresh   28  Bengaluru
2  Satish   35    Chennai

In [109]:
# Rename all the columns
df.columns=['A','B','C']
df

        A   B          C
0  Ramesh  30        Hyd
1  Suresh  28  Bengaluru
2  Satish  35    Chennai

In [111]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [113]:
df.index=['A','B','C']
df

        A   B          C
A  Ramesh  30        Hyd
B  Suresh  28  Bengaluru
C  Satish  35    Chennai

In [115]:
dict1={'Names':['Ramesh','Suresh','Satish'],
        'Age':[30,28,35],
        'city':['Hyd','Bengaluru','Chennai']}
df=pd.DataFrame(dict1)
df

    Names  Age       city
0  Ramesh   30        Hyd
1  Suresh   28  Bengaluru
2  Satish   35    Chennai

In [117]:
# df.rename(mapper,index,columns,axis,inplace)
d={'Names':'A','Age':'B','City':'C'}
df.rename(d)

    Names  Age       city
0  Ramesh   30        Hyd
1  Suresh   28  Bengaluru
2  Satish   35    Chennai

In [123]:
# df.rename(mapper,index,columns,axis,inplace)
d={'Names':'A','Age':'B','City':'C'}
df.rename(d,inplace=True)
df

    Names  Age       city
0  Ramesh   30        Hyd
1  Suresh   28  Bengaluru
2  Satish   35    Chennai

In [125]:
# df.rename(mapper,index,columns,axis,inplace)
d={'Names':'A','Age':'B','City':'C'}
df.rename(columns=d,inplace=True)
df

        A   B       city
0  Ramesh  30        Hyd
1  Suresh  28  Bengaluru
2  Satish  35    Chennai

In [127]:
# df.rename(mapper,index,columns,axis,inplace)
dict1={'Names':['Ramesh','Suresh','Satish'],
        'Age':[30,28,35],
        'city':['Hyd','Bengaluru','Chennai']}
df=pd.DataFrame(dict1)
d={'Names':'A','Age':'B','City':'C'}
df.rename(columns=d,inplace=True)
df

        A   B       city
0  Ramesh  30        Hyd
1  Suresh  28  Bengaluru
2  Satish  35    Chennai

In [129]:
# df.rename(mapper,index,columns,axis,inplace)
dict1={'Names':['Ramesh','Suresh','Satish'],
        'Age':[30,28,35],
        'city':['Hyd','Bengaluru','Chennai']}
df=pd.DataFrame(dict1)
d={0:'A',1:'B',2:'C'}
df.rename(columns=d,inplace=True)
df

    Names  Age       city
0  Ramesh   30        Hyd
1  Suresh   28  Bengaluru
2  Satish   35    Chennai

In [131]:
# df.rename(mapper,index,columns,axis,inplace)
dict1={'Names':['Ramesh','Suresh','Satish'],
        'Age':[30,28,35],
        'city':['Hyd','Bengaluru','Chennai']}
df=pd.DataFrame(dict1)
d={'Names':'A','Age':'B','City':'C'}
df.rename(d,inplace=True)
df.rename(d,axis=1,inplace=True)
df

        A   B       city
0  Ramesh  30        Hyd
1  Suresh  28  Bengaluru
2  Satish  35    Chennai