In [1]:
import pandas as pd
import numpy as np

In [3]:
dict1={'Name':['Ramesh','Suresh','Sathish',np.nan],
       'Age':[30,33,np.nan,36],
       'City':[np.nan,'Hyd','Hyd','Blr']}

In [5]:
data=pd.DataFrame(dict1)
data

      Name   Age City
0   Ramesh  30.0  NaN
1   Suresh  33.0  Hyd
2  Sathish   NaN  Hyd
3      NaN  36.0  Blr

In [15]:
data.to_csv('dataa.csv',index=False)

In [17]:
data.isnull()

    Name    Age   City
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

In [19]:
data.isnull().sum()

Name    1
Age     1
City    1
dtype: int64

# dropna :
- drop the null values data based on rows and columns

In [23]:
# We want to extract the data without Null values
data.dropna()

     Name   Age City
1  Suresh  33.0  Hyd

In [30]:
data

      Name   Age City
0   Ramesh  30.0  NaN
1   Suresh  33.0  Hyd
2  Sathish   NaN  Hyd
3      NaN  36.0  Blr

In [32]:
data.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [34]:
dict1={'Name':['Ramesh','Suresh','Sathish',np.nan],
       'Age':[30,33,np.nan,36],
       'City':[np.nan,'Hyd','Hyd','Blr'],
       'Company':['Google','Microsoft','Apple','Meta']
      }
data1=pd.DataFrame(dict1)
data1

      Name   Age City    Company
0   Ramesh  30.0  NaN     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish   NaN  Hyd      Apple
3      NaN  36.0  Blr       Meta

# Fillna :

In [41]:
data1.fillna(30)

      Name   Age City    Company
0   Ramesh  30.0   30     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  30.0  Hyd      Apple
3       30  36.0  Blr       Meta

In [43]:
# ist select the column , then apply Fillna
data1['Name'].fillna('Hari')

0     Ramesh
1     Suresh
2    Sathish
3       Hari
Name: Name, dtype: object

# Drawback : Filling with Random value is not a Good approach
- To avoid that we have some methods
  
  - backfill
    
  - bfill
 
  - ffill
 
  - pad

# pad :

In [51]:
data1.fillna(method='pad')

C:\Users\TSTRANSCO\AppData\Local\Temp\ipykernel_5168\116358274.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1.fillna(method='pad')

      Name   Age City    Company
0   Ramesh  30.0  NaN     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  33.0  Hyd      Apple
3  Sathish  36.0  Blr       Meta

In [53]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='pad')

      Name   Age City    Company
0   Ramesh  30.0  NaN     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  33.0  Hyd      Apple
3  Sathish  36.0  Blr       Meta

In [57]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='pad',axis=1) # axis =1 Column wise

      Name      Age  City    Company
0   Ramesh     30.0  30.0     Google
1   Suresh     33.0   Hyd  Microsoft
2  Sathish  Sathish   Hyd      Apple
3      NaN     36.0   Blr       Meta

# backfill :

In [62]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='backfill')

      Name   Age City    Company
0   Ramesh  30.0  Hyd     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  36.0  Hyd      Apple
3      NaN  36.0  Blr       Meta

In [64]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='backfill',axis=1)

      Name   Age    City    Company
0   Ramesh  30.0  Google     Google
1   Suresh  33.0     Hyd  Microsoft
2  Sathish   Hyd     Hyd      Apple
3     36.0  36.0     Blr       Meta

# bfill :

In [67]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='bfill')

      Name   Age City    Company
0   Ramesh  30.0  Hyd     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  36.0  Hyd      Apple
3      NaN  36.0  Blr       Meta

In [69]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='bfill',axis=1)

      Name   Age    City    Company
0   Ramesh  30.0  Google     Google
1   Suresh  33.0     Hyd  Microsoft
2  Sathish   Hyd     Hyd      Apple
3     36.0  36.0     Blr       Meta

# ffill :

In [72]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='ffill')

      Name   Age City    Company
0   Ramesh  30.0  NaN     Google
1   Suresh  33.0  Hyd  Microsoft
2  Sathish  33.0  Hyd      Apple
3  Sathish  36.0  Blr       Meta

In [74]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='ffill',axis=1)

      Name      Age  City    Company
0   Ramesh     30.0  30.0     Google
1   Suresh     33.0   Hyd  Microsoft
2  Sathish  Sathish   Hyd      Apple
3      NaN     36.0   Blr       Meta

- **backfill :** Assigns value to previous numm

- **ffill :** Assigns value to next null

# Mean - Median - Mode :

In [79]:
# STEP - 1 : Select the column
# STEP - 2 : Get the Mean
# STEP - 3 : Apply fill na

age_mean=data1['Age'].mean()
print('age_mean: ',age_mean)
data1['Age'].fillna(age_mean)

age_mean:  33.0

0    30.0
1    33.0
2    33.0
3    36.0
Name: Age, dtype: float64

In [ ]:
city_mode=data1['Age'].mode()

# impute :

KNN : 

K - Nearest neighbours [ k means **numbers** ]

How many neighbours we want to choose

In [82]:
import numpy as np
from sklearn.impute import KNNImputer
X = [[1,2, np.nan], [3, np.nan, 3], [np.nan, 60, 5], [8,8,7]]
pd.DataFrame(X)

     0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [88]:
import numpy as np
from sklearn.impute import KNNImputer
X = [[1,2, np.nan], [3, np.nan, 3], [np.nan, 60, 5], [8,8,7]]
imputer = KNNImputer(n_neighbors=2,weights='distance')
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])

In [90]:
import numpy as np
from sklearn.impute import KNNImputer
X = [[1,2, np.nan], [3, np.nan, 3], [np.nan, 60, 5], [8,8,7]]
imputer = KNNImputer(n_neighbors=2,weights='uniform')
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])