<h1><center><b>Missing Value Analysis</b></center></h1>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

visa_df=pd.read_csv(r"E:\Python Projects\Data Files\Visadataset.csv")

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

cat,num

(Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
        'requires_job_training', 'region_of_employment', 'unit_of_wage',
        'full_time_position', 'case_status'],
       dtype='object'),
 Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object'))

In [15]:
dict1 = {'Name':['Akash','Rocky','Kushal',np.nan],
        'Age':[20,21,np.nan,23],
        'City':[np.nan,'Hyderabad','Hyderabad','Mumbai']}
data1 = pd.DataFrame(dict1)
data1

     Name   Age       City
0   Akash  20.0        NaN
1   Rocky  21.0  Hyderabad
2  Kushal   NaN  Hyderabad
3     NaN  23.0     Mumbai

In [17]:
data1.to_csv('data11111.csv',index=False)

In [19]:
data1.isnull()

    Name    Age   City
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

In [21]:
data1.isnull().sum()

Name    1
Age     1
City    1
dtype: int64

# dropna :
- Drop the null value data, based on rows and columns

In [23]:
# I want to extract the data without NULL VALUES
# axis = 0 means The Null Value will be removed based on Row
# axis = 1 means The Null Value will be removed based on Column

data1.dropna()

    Name   Age       City
1  Rocky  21.0  Hyderabad

In [25]:
data1.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [27]:
dict2 = {'Name':['Akash','Rocky','Kushal',np.nan],
        'Age':[20,21,np.nan,23],
        'City':[np.nan,'Hyderabad','Hyderabad','Mumbai'],
        'Company':['Google','Microsoft','Apple','Meta']}
data2 = pd.DataFrame(dict2)
data2

     Name   Age       City    Company
0   Akash  20.0        NaN     Google
1   Rocky  21.0  Hyderabad  Microsoft
2  Kushal   NaN  Hyderabad      Apple
3     NaN  23.0     Mumbai       Meta

In [29]:
data2.dropna(axis=1)

     Company
0     Google
1  Microsoft
2      Apple
3       Meta

# fillna() :

In [33]:
data2.fillna(30)

     Name   Age       City    Company
0   Akash  20.0         30     Google
1   Rocky  21.0  Hyderabad  Microsoft
2  Kushal  30.0  Hyderabad      Apple
3      30  23.0     Mumbai       Meta

# NOTE :
- The drawback is it add the value in every empty data location
- Even at **name** and **city**

In [39]:
data2['Name'].fillna('Rohit')

0     Akash
1     Rocky
2    Kushal
3     Rohit
Name: Name, dtype: object

- Drawback : Filling with Random value is not a Good Approch
- To avoid that we have some methods
    - backfill
    - bfill
    - ffill
    - pad

In [44]:
import warnings
warnings.filterwarnings('ignore')
print(data2.fillna(method='pad',axis=1))
print()
print(data2.fillna(method='pad'))

     Name     Age       City    Company
0   Akash    20.0       20.0     Google
1   Rocky    21.0  Hyderabad  Microsoft
2  Kushal  Kushal  Hyderabad      Apple
3     NaN    23.0     Mumbai       Meta

     Name   Age       City    Company
0   Akash  20.0        NaN     Google
1   Rocky  21.0  Hyderabad  Microsoft
2  Kushal  21.0  Hyderabad      Apple
3  Kushal  23.0     Mumbai       Meta

In [46]:
import warnings
warnings.filterwarnings('ignore')
print(data2.fillna(method='ffill',axis=1))
print()
print(data2.fillna(method='ffill'))

     Name     Age       City    Company
0   Akash    20.0       20.0     Google
1   Rocky    21.0  Hyderabad  Microsoft
2  Kushal  Kushal  Hyderabad      Apple
3     NaN    23.0     Mumbai       Meta

     Name   Age       City    Company
0   Akash  20.0        NaN     Google
1   Rocky  21.0  Hyderabad  Microsoft
2  Kushal  21.0  Hyderabad      Apple
3  Kushal  23.0     Mumbai       Meta

In [48]:
import warnings
warnings.filterwarnings('ignore')
print(data2.fillna(method='backfill',axis=1))
print()
print(data2.fillna(method='backfill'))

     Name        Age       City    Company
0   Akash       20.0     Google     Google
1   Rocky       21.0  Hyderabad  Microsoft
2  Kushal  Hyderabad  Hyderabad      Apple
3    23.0       23.0     Mumbai       Meta

     Name   Age       City    Company
0   Akash  20.0  Hyderabad     Google
1   Rocky  21.0  Hyderabad  Microsoft
2  Kushal  23.0  Hyderabad      Apple
3     NaN  23.0     Mumbai       Meta

In [50]:
import warnings
warnings.filterwarnings('ignore')
print(data2.fillna(method='bfill',axis=1))
print()
print(data2.fillna(method='bfill'))

     Name        Age       City    Company
0   Akash       20.0     Google     Google
1   Rocky       21.0  Hyderabad  Microsoft
2  Kushal  Hyderabad  Hyderabad      Apple
3    23.0       23.0     Mumbai       Meta

     Name   Age       City    Company
0   Akash  20.0  Hyderabad     Google
1   Rocky  21.0  Hyderabad  Microsoft
2  Kushal  23.0  Hyderabad      Apple
3     NaN  23.0     Mumbai       Meta

# Mean - Median - Mode :

- **Step 1 :** Select the **COLUMN**
- **Step 2 :** Get the **MEAN**
- **Step 3 :** Apply **fillna()**

In [55]:
age_mean = round(data2['Age'].mean(),2)
print('age_mean :',age_mean)
data2['Age'].fillna(age_mean)

age_mean : 21.33

0    20.00
1    21.00
2    21.33
3    23.00
Name: Age, dtype: float64

In [57]:
city_mode = data2['City'].mode()

print('age_mode :',city_mode.values[0])
data2['City'].fillna(city_mode.values[0])

age_mode : Hyderabad

0    Hyderabad
1    Hyderabad
2    Hyderabad
3       Mumbai
Name: City, dtype: object

In [59]:
from sklearn.impute import KNNImputer
x = [[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(x)

     0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [61]:
from sklearn.impute import KNNImputer
x = [[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer = KNNImputer(n_neighbors=2,weights='uniform')
imputer.fit_transform(x)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [63]:
from sklearn.impute import KNNImputer
x = [[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer = KNNImputer(n_neighbors=2,weights='distance')
imputer.fit_transform(x)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])