In [1]:
!pip install azure-storage-blob PyMuPDF PyPDF2 fitz

Collecting azure-storage-blob
  Downloading azure_storage_blob-12.27.1-py3-none-any.whl.metadata (26 kB)
Collecting PyMuPDF
  Downloading pymupdf-1.26.6-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Collecting fitz
  Downloading fitz-0.0.1.dev2-py2.py3-none-any.whl.metadata (816 bytes)
Collecting azure-core>=1.30.0 (from azure-storage-blob)
  Downloading azure_core-1.36.0-py3-none-any.whl.metadata (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.1/47.1 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python3.12/dist-packages (from azure-storage-blob) (43.0.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from azure-storage-blob) (4.15.0)
Collecting isodate>=0.6.1 (from azure-storage-blob)
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Collecting configobj (from fitz)
  Downloading configobj-5.0.9-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting configparser (from fitz)
  Downloading configparser-7.2.0-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: httplib2 in /usr/local/lib/python3.12/dist-packages (from fitz) (0.31.0)
Requirement already satisfied: nibabel in /usr/local/lib/python3.12/dist-packages (from fitz) (5.3.2)
Collecting nipype (from fitz)
  Downloading nipype-1.10.0-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fitz) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from fitz) (2.2.2)
Collecting pyxnat (from fitz)
  Downloading pyxnat-1.6.4-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from fitz) (1.16.3)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from azure-core>=1.30.0->azure-storage-blob) (2.32.4)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=2.1.4->azure-storage-blob) (2.0.0)
Requirement already satisfied: pyparsing<4,>=3.0.4 in /usr/local/lib/python3.12/dist-packages (from httplib2->fitz) (3.2.5)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from nibabel->fitz) (25.0)
Requirement already satisfied: click>=6.6.0 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (8.3.0)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (3.5)
Collecting prov>=1.5.2 (from nipype->fitz)
  Downloading prov-2.1.1-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: pydot>=1.2.3 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (3.0.4)
Requirement already satisfied: python-dateutil>=2.2 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (2.9.0.post0)
Collecting rdflib>=5.0.0 (from nipype->fitz)
  Downloading rdflib-7.4.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: simplejson>=3.8.0 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (3.20.2)
Collecting traits>=6.2 (from nipype->fitz)
  Downloading traits-7.0.2-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: filelock>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (3.20.0)
Collecting acres (from nipype->fitz)
  Downloading acres-0.5.0-py3-none-any.whl.metadata (6.2 kB)
Collecting etelemetry>=0.3.1 (from nipype->fitz)
  Downloading etelemetry-0.3.1-py3-none-any.whl.metadata (3.2 kB)
Collecting looseversion!=1.2 (from nipype->fitz)
  Downloading looseversion-1.3.0-py2.py3-none-any.whl.metadata (4.6 kB)
Collecting puremagic (from nipype->fitz)
  Downloading puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->fitz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->fitz) (2025.2)
Requirement already satisfied: lxml>=4.3 in /usr/local/lib/python3.12/dist-packages (from pyxnat->fitz) (5.4.0)
Collecting pathlib>=1.0 (from pyxnat->fitz)
  Downloading pathlib-1.0.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=2.1.4->azure-storage-blob) (2.23)
Collecting ci-info>=0.2 (from etelemetry>=0.3.1->nipype->fitz)
  Downloading ci_info-0.3.0-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.2->nipype->fitz) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob) (2025.10.5)
Downloading azure_storage_blob-12.27.1-py3-none-any.whl (428 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 429.0/429.0 kB 7.2 MB/s eta 0:00:00
Downloading pymupdf-1.26.6-cp310-abi3-manylinux_2_28_x86_64.whl (24.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 22.4 MB/s eta 0:00:00
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 9.7 MB/s eta 0:00:00
Downloading fitz-0.0.1.dev2-py2.py3-none-any.whl (20 kB)
Downloading azure_core-1.36.0-py3-none-any.whl (213 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.3/213.3 kB 9.3 MB/s eta 0:00:00
Downloading isodate-0.7.2-py3-none-any.whl (22 kB)
Downloading configobj-5.0.9-py2.py3-none-any.whl (35 kB)
Downloading configparser-7.2.0-py3-none-any.whl (17 kB)
Downloading nipype-1.10.0-py3-none-any.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 87.7 MB/s eta 0:00:00
Downloading pyxnat-1.6.4-py3-none-any.whl (110 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.7/110.7 kB 9.6 MB/s eta 0:00:00
Downloading etelemetry-0.3.1-py3-none-any.whl (6.4 kB)
Downloading looseversion-1.3.0-py2.py3-none-any.whl (8.2 kB)
Downloading pathlib-1.0.1-py3-none-any.whl (14 kB)
Downloading prov-2.1.1-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.9/425.9 kB 31.1 MB/s eta 0:00:00
Downloading rdflib-7.4.0-py3-none-any.whl (569 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 569.0/569.0 kB 31.0 MB/s eta 0:00:00
Downloading traits-7.0.2-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 97.9 MB/s eta 0:00:00
Downloading acres-0.5.0-py3-none-any.whl (12 kB)
Downloading puremagic-1.30-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 3.1 MB/s eta 0:00:00
Downloading ci_info-0.3.0-py3-none-any.whl (7.8 kB)
Installing collected packages: puremagic, pathlib, looseversion, traits, rdflib, PyPDF2, PyMuPDF, isodate, configparser, configobj, ci-info, acres, pyxnat, prov, etelemetry, azure-core, nipype, azure-storage-blob, fitz
Successfully installed PyMuPDF-1.26.6 PyPDF2-3.0.1 acres-0.5.0 azure-core-1.36.0 azure-storage-blob-12.27.1 ci-info-0.3.0 configobj-5.0.9 configparser-7.2.0 etelemetry-0.3.1 fitz-0.0.1.dev2 isodate-0.7.2 looseversion-1.3.0 nipype-1.10.0 pathlib-1.0.1 prov-2.1.1 puremagic-1.30 pyxnat-1.6.4 rdflib-7.4.0 traits-7.0.2

In [1]:
import azure.storage.blob

In [ ]:
# what are the methods are there inside the package
dir(azure.storage.blob)

['AccessPolicy',
 'AccountSasPermissions',
 'Any',
 'AnyStr',
 'ArrowDialect',
 'ArrowType',
 'BlobAnalyticsLogging',
 'BlobBlock',
 'BlobClient',
 'BlobImmutabilityPolicyMode',
 'BlobLeaseClient',
 'BlobPrefix',
 'BlobProperties',
 'BlobQueryError',
 'BlobQueryReader',
 'BlobSasPermissions',
 'BlobServiceClient',
 'BlobType',
 'BlockState',
 'ContainerClient',
 'ContainerEncryptionScope',
 'ContainerProperties',
 'ContainerSasPermissions',
 'ContentSettings',
 'CopyProperties',
 'CorsRule',
 'CustomerProvidedEncryptionKey',
 'DelimitedJsonDialect',
 'DelimitedTextDialect',
 'Dict',
 'ExponentialRetry',
 'FilteredBlob',
 'IO',
 'ImmutabilityPolicy',
 'Iterable',
 'LeaseProperties',
 'LinearRetry',
 'LocationMode',
 'Metrics',
 'ObjectReplicationPolicy',
 'ObjectReplicationRule',
 'Optional',
 'PageRange',
 'PartialBatchErrorException',
 'PremiumPageBlobTier',
 'PublicAccess',
 'QuickQueryDialect',
 'RehydratePriority',
 'ResourceTypes',
 'RetentionPolicy',
 'SequenceNumberAction',
 'Services',
 'StandardBlobTier',
 'StaticWebsite',
 'StorageErrorCode',
 'StorageStreamDownloader',
 'TYPE_CHECKING',
 'Union',
 'UserDelegationKey',
 'VERSION',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_blob_client',
 '_blob_client_helpers',
 '_blob_service_client',
 '_blob_service_client_helpers',
 '_container_client',
 '_container_client_helpers',
 '_deserialize',
 '_download',
 '_download_to_stream',
 '_encryption',
 '_generated',
 '_lease',
 '_list_blobs_helper',
 '_models',
 '_quick_query_helper',
 '_serialize',
 '_shared',
 '_shared_access_signature',
 '_upload_helpers',
 '_version',
 'cast',
 'download_blob_from_url',
 'generate_account_sas',
 'generate_blob_sas',
 'generate_container_sas',
 'os',
 'upload_blob_to_url']

In [ ]:
# Method_name: BlobServiceClient

**Container operations**

$1$.$Create$ $Container$

In [2]:
from azure.storage.blob import BlobServiceClient

In [ ]:
#help(BlobServiceClient)
# BlobServiceClient expecting two main arguments
# account_url: every storage service has one url
# "https://<storage_service_name>.blob.core.windows.net/"
# "https://vgp25.blob.core.windows.net/"
# https://nareshitblob.blob.core.windows.net/
# this will give information to the Blobserviceclient on which storage service it will
# you need to work on a storage account ===== > who will give the permission to enter inside the storage account

# credential

In [ ]:
# please login to portal.azure.com
# on which storage account you need to work go to that storage: storageforde
# under the essential ==== json view will be avialable
#blob_account_url="https://storageforde.blob.core.windows.net/"
#storage_credential="MfHfi/aTTNq/jNoyz31qA89Hy7c4N24TspPqeML99eyPS9mhOsQ6cOH0hUhbmReeg3TFGfx7CdjH+AStMYaESQ=="

https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal

In [ ]:
"https://nareshitmorningbatch.blob.core.windows.net/",

In [ ]:
blob_account_url="https://nareshitblob.blob.core.windows.net/"
storage_credential="hnclryr5KBlXTFUXdJhMeXXwS347QJ0Dthf6yFvUEBJ6foY5lVnGc07HqTcSEh5QclBfIEvKID7Q+AStDA4ctg=="

In [ ]:
blob_service_client=BlobServiceClient(account_url=blob_account_url,
                                      credential=storage_credential)

blob_service_client

In [ ]:
#dir(blob_service_client)

In [ ]:
#help(blob_service_client.create_container)

In [ ]:
new_container=blob_service_client.create_container('nareshitomkarcontainer')
new_container

In [ ]:
#all together
from azure.storage.blob import BlobServiceClient
blob_account_url="https://nareshitblob.blob.core.windows.net/"
storage_credential="hnclryr5KBlXTFUXdJhMeXXwS347QJ0Dthf6yFvUEBJ6foY5lVnGc07HqTcSEh5QclBfIEvKID7Q+AStDA4ctg=="
blob_service_client=BlobServiceClient(account_url=blob_account_url,
                                      credential=storage_credential)

new_container=blob_service_client.create_container('pythonnareshit2',public_access='Container')
new_container

# by default it will take the private

In [ ]:
new_container.get_container_properties()

{'name': 'pythonnareshit2', 'last_modified': datetime.datetime(2025, 11, 18, 6, 0, 17, tzinfo=datetime.timezone.utc), 'etag': '"0x8DE2667BF8C29BA"', 'lease': {'status': 'unlocked', 'state': 'available', 'duration': None}, 'public_access': 'container', 'has_immutability_policy': False, 'deleted': None, 'version': None, 'has_legal_hold': False, 'metadata': {}, 'encryption_scope': <azure.storage.blob._models.ContainerEncryptionScope object at 0x7988f9531d60>, 'immutable_storage_with_versioning_enabled': False}

In [ ]:
type(new_container.get_container_properties())

azure.storage.blob._models.ContainerProperties

In [ ]:
pandas.DataFrame({'name':'Ram','age':30},index=['0'])

  name  age
0  Ram   30

$Step-2$: **List out all containers**

In [ ]:
all_containers=blob_service_client.list_containers()
all_containers

# the variable is a iterator, you need to get outputs by using for loop
for container in all_containers:
    print(container)

{'name': 'nareshitcontainer', 'last_modified': datetime.datetime(2025, 11, 17, 6, 24, 55, tzinfo=datetime.timezone.utc), 'etag': '"0x8DE25A2069BD688"', 'lease': {'status': 'unlocked', 'state': 'available', 'duration': None}, 'public_access': 'blob', 'has_immutability_policy': False, 'deleted': None, 'version': None, 'has_legal_hold': False, 'metadata': None, 'encryption_scope': <azure.storage.blob._models.ContainerEncryptionScope object at 0x7988f808f6b0>, 'immutable_storage_with_versioning_enabled': False}
{'name': 'nareshitomkarcontainer', 'last_modified': datetime.datetime(2025, 11, 18, 5, 57, 10, tzinfo=datetime.timezone.utc), 'etag': '"0x8DE26675082CFA7"', 'lease': {'status': 'unlocked', 'state': 'available', 'duration': None}, 'public_access': None, 'has_immutability_policy': False, 'deleted': None, 'version': None, 'has_legal_hold': False, 'metadata': None, 'encryption_scope': <azure.storage.blob._models.ContainerEncryptionScope object at 0x7988f95a0b60>, 'immutable_storage_with_versioning_enabled': False}
{'name': 'pythonnareshit2', 'last_modified': datetime.datetime(2025, 11, 18, 6, 0, 17, tzinfo=datetime.timezone.utc), 'etag': '"0x8DE2667BF8C29BA"', 'lease': {'status': 'unlocked', 'state': 'available', 'duration': None}, 'public_access': 'container', 'has_immutability_policy': False, 'deleted': None, 'version': None, 'has_legal_hold': False, 'metadata': None, 'encryption_scope': <azure.storage.blob._models.ContainerEncryptionScope object at 0x7988fa03bcb0>, 'immutable_storage_with_versioning_enabled': False}

In [ ]:
all_containers

In [ ]:
all_containers=blob_service_client.list_containers()
all_containers

# the variable is a iterator, you need to get outputs by using for loop
for container in all_containers:
    print(container['name'])

nareshitomkarcontainer
pythonnareshit2
vgpcontainer

In [ ]:
container['name']

'pythonnareshit2'

$Step-3$:**Delete the contaiers**

In [ ]:
blob_service_client.delete_container('nareshitomkarcontainer')

In [ ]:
#all together
from azure.storage.blob import BlobServiceClient
blob_account_url="https://storageforde.blob.core.windows.net/"
storage_credential="MfHfi/aTTNq/jNoyz31qA89Hy7c4N24TspPqeML99eyPS9mhOsQ6cOH0hUhbmReeg3TFGfx7CdjH+AStMYaESQ=="
blob_service_client=BlobServiceClient(account_url=blob_account_url,
                                      credential=storage_credential)

new_container=blob_service_client.create_container('pythonnareshit1',public_access='Container')
new_container

In [ ]:
all_containers=blob_service_client.list_containers()
for container in all_containers:
    print("deleting:",container['name'])
    blob_service_client.delete_container(container['name'])

deleting: pythonnareshit1
deleting: pythonnareshit2
deleting: pythonnareshit3

Blobserviceclint getting the access using account url and credentials

- Account_url frm under essentials from the json view

- Credntials : Unnder access keys we havec key

### In the same way we can able to access storage accounts using connection string

$From$ $connection$ $string$

In [ ]:
# from azure.storage.blob import BlobServiceClient
# connection_string='DefaultEndpointsProtocol=https;AccountName=storageforde;AccountKey=MfHfi/aTTNq/jNoyz31qA89Hy7c4N24TspPqeML99eyPS9mhOsQ6cOH0hUhbmReeg3TFGfx7CdjH+AStMYaESQ==;EndpointSuffix=core.windows.net'
# blob_service_client_using_connection_string=BlobServiceClient.from_connection_string(connection_string)
# blob_service_client_using_connection_string

In [ ]:
# from azure.storage.blob import BlobServiceClient
# blob_account_url="https://vgp25.blob.core.windows.net/"
# storage_credential="MfHfi/aTTNq/jNoyz31qA89Hy7c4N24TspPqeML99eyPS9mhOsQ6cOH0hUhbmReeg3TFGfx7CdjH+AStMYaESQ=="
# blob_service_client=BlobServiceClient(account_url=blob_account_url,
#                                       credential=storage_credential)

# #=============================================================================
# from azure.storage.blob import BlobServiceClient
# connection_string='DefaultEndpointsProtocol=https;AccountName=storageforde;AccountKey=MfHfi/aTTNq/jNoyz31qA89Hy7c4N24TspPqeML99eyPS9mhOsQ6cOH0hUhbmReeg3TFGfx7CdjH+AStMYaESQ==;EndpointSuffix=core.windows.net'
# blob_service_client_using_connection_string=BlobServiceClient.from_connection_string(connection_string)
# blob_service_client_using_connection_string

In [ ]:
blob_service_client_using_connection_string.get_account_information()

{'client_request_id': 'f37e4492-0f8a-11ee-97d8-0242ac1c000c',
 'request_id': 'd40cc8d2-f01e-0037-3497-a37e91000000',
 'version': '2022-11-02',
 'date': datetime.datetime(2023, 6, 20, 16, 53, 15, tzinfo=datetime.timezone.utc),
 'sku_name': 'Standard_LRS',
 'account_kind': 'StorageV2',
 'is_hns_enabled': False}

In [ ]:
# blobs =====> data files inside the container
# storage_account_name= storageforde
# container_name=pythonnareshit1
# blob= bank.csv

**get_container_client**: to interact with container

In [3]:
from azure.storage.blob import BlobServiceClient
connection_string='DefaultEndpointsProtocol=https;AccountName=nareshitblob;AccountKey=hnclryr5KBlXTFUXdJhMeXXwS347QJ0Dthf6yFvUEBJ6foY5lVnGc07HqTcSEh5QclBfIEvKID7Q+AStDA4ctg==;EndpointSuffix=core.windows.net'
blob_service_client_using_connection_string=BlobServiceClient.from_connection_string(connection_string)
blob_service_client_using_connection_string

In [4]:
container_client=blob_service_client_using_connection_string \
                 .get_container_client("nareshitcontainer")
container_client

In [5]:
for blob in container_client.list_blobs():
    print(blob)

{'name': 'Attention_all_you_need.pdf', 'container': 'nareshitcontainer', 'snapshot': None, 'version_id': None, 'is_current_version': None, 'blob_type': <BlobType.BLOCKBLOB: 'BlockBlob'>, 'metadata': {}, 'encrypted_metadata': None, 'last_modified': datetime.datetime(2025, 11, 17, 6, 17, 21, tzinfo=datetime.timezone.utc), 'etag': '0x8DE25A0F80F54B4', 'size': 2215244, 'content_range': None, 'append_blob_committed_block_count': None, 'is_append_blob_sealed': None, 'page_blob_sequence_number': None, 'server_encrypted': True, 'copy': {'id': None, 'source': None, 'status': None, 'progress': None, 'completion_time': None, 'status_description': None, 'incremental_copy': None, 'destination_snapshot': None}, 'content_settings': {'content_type': 'application/pdf', 'content_encoding': None, 'content_language': None, 'content_md5': bytearray(b'\x18\xe1\xb0\x07\xa1\xda\xb4[0\xcc\x86\x1b\xa2\xdf\xda%'), 'content_disposition': None, 'cache_control': None}, 'lease': {'status': 'unlocked', 'state': 'available', 'duration': None}, 'blob_tier': 'Hot', 'rehydrate_priority': None, 'blob_tier_change_time': None, 'blob_tier_inferred': True, 'deleted': None, 'deleted_time': None, 'remaining_retention_days': None, 'creation_time': datetime.datetime(2025, 11, 17, 6, 17, 21, tzinfo=datetime.timezone.utc), 'archive_status': None, 'encryption_key_sha256': None, 'encryption_scope': None, 'request_server_encrypted': None, 'object_replication_source_properties': [], 'object_replication_destination_policy': None, 'last_accessed_on': None, 'tag_count': None, 'tags': None, 'immutability_policy': {'expiry_time': None, 'policy_mode': None}, 'has_legal_hold': None, 'has_versions_only': None}

In [6]:
container_client=blob_service_client_using_connection_string \
                 .get_container_client("nareshitcontainer")
for blob in container_client.list_blobs():
    print(blob['name'])

Attention_all_you_need.pdf

**get_blob_client**: to interact with blob

## Pdf data

In [7]:
blob_client=blob_service_client_using_connection_string \
            .get_blob_client("nareshitcontainer","Attention_all_you_need.pdf")

pdf_data=blob_client.download_blob()
pdf_bytes=pdf_data.readall()
len(pdf_bytes)

2215244

In [ ]:
#!pip install PyPDF2

In [8]:
from PyPDF2 import PdfReader
import io
pdf_reader=PdfReader(io.BytesIO(pdf_bytes))
print(pdf_reader.pages[2].extract_text())

Figure 1: The Transformer - model architecture.
The Transformer follows this overall architecture using stacked self-attention and point-wise, fully
connected layers for both the encoder and decoder, shown in the left and right halves of Figure 1,
respectively.
3.1 Encoder and Decoder Stacks
Encoder: The encoder is composed of a stack of N= 6 identical layers. Each layer has two
sub-layers. The first is a multi-head self-attention mechanism, and the second is a simple, position-
wise fully connected feed-forward network. We employ a residual connection [ 11] around each of
the two sub-layers, followed by layer normalization [ 1]. That is, the output of each sub-layer is
LayerNorm( x+ Sublayer( x)), where Sublayer( x)is the function implemented by the sub-layer
itself. To facilitate these residual connections, all sub-layers in the model, as well as the embedding
layers, produce outputs of dimension dmodel = 512 .
Decoder: The decoder is also composed of a stack of N= 6identical layers. In addition to the two
sub-layers in each encoder layer, the decoder inserts a third sub-layer, which performs multi-head
attention over the output of the encoder stack. Similar to the encoder, we employ residual connections
around each of the sub-layers, followed by layer normalization. We also modify the self-attention
sub-layer in the decoder stack to prevent positions from attending to subsequent positions. This
masking, combined with fact that the output embeddings are offset by one position, ensures that the
predictions for position ican depend only on the known outputs at positions less than i.
3.2 Attention
An attention function can be described as mapping a query and a set of key-value pairs to an output,
where the query, keys, values, and output are all vectors. The output is computed as a weighted sum
3

- PyPDF2 is not extracting images

- for that we need to use Pymupdf and fitz

In [12]:
!pip install fitz

Requirement already satisfied: fitz in /usr/local/lib/python3.12/dist-packages (0.0.1.dev2)
Requirement already satisfied: configobj in /usr/local/lib/python3.12/dist-packages (from fitz) (5.0.9)
Requirement already satisfied: configparser in /usr/local/lib/python3.12/dist-packages (from fitz) (7.2.0)
Requirement already satisfied: httplib2 in /usr/local/lib/python3.12/dist-packages (from fitz) (0.31.0)
Requirement already satisfied: nibabel in /usr/local/lib/python3.12/dist-packages (from fitz) (5.3.2)
Requirement already satisfied: nipype in /usr/local/lib/python3.12/dist-packages (from fitz) (1.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fitz) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from fitz) (2.2.2)
Requirement already satisfied: pyxnat in /usr/local/lib/python3.12/dist-packages (from fitz) (1.6.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from fitz) (1.16.3)
Requirement already satisfied: pyparsing<4,>=3.0.4 in /usr/local/lib/python3.12/dist-packages (from httplib2->fitz) (3.2.5)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from nibabel->fitz) (25.0)
Requirement already satisfied: typing-extensions>=4.6 in /usr/local/lib/python3.12/dist-packages (from nibabel->fitz) (4.15.0)
Requirement already satisfied: click>=6.6.0 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (8.3.0)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (3.5)
Requirement already satisfied: prov>=1.5.2 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (2.1.1)
Requirement already satisfied: pydot>=1.2.3 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (3.0.4)
Requirement already satisfied: python-dateutil>=2.2 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (2.9.0.post0)
Requirement already satisfied: rdflib>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (7.4.0)
Requirement already satisfied: simplejson>=3.8.0 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (3.20.2)
Requirement already satisfied: traits>=6.2 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (7.0.2)
Requirement already satisfied: filelock>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (3.20.0)
Requirement already satisfied: acres in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (0.5.0)
Requirement already satisfied: etelemetry>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (0.3.1)
Requirement already satisfied: looseversion!=1.2 in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (1.3.0)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from nipype->fitz) (1.30)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->fitz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->fitz) (2025.2)
Requirement already satisfied: lxml>=4.3 in /usr/local/lib/python3.12/dist-packages (from pyxnat->fitz) (5.4.0)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.12/dist-packages (from pyxnat->fitz) (2.32.4)
Requirement already satisfied: pathlib>=1.0 in /usr/local/lib/python3.12/dist-packages (from pyxnat->fitz) (1.0.1)
Requirement already satisfied: ci-info>=0.2 in /usr/local/lib/python3.12/dist-packages (from etelemetry>=0.3.1->nipype->fitz) (0.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.2->nipype->fitz) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->pyxnat->fitz) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->pyxnat->fitz) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->pyxnat->fitz) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->pyxnat->fitz) (2025.10.5)

In [19]:
import fitz  # PyMuPDF
import io

doc = fitz.open(stream=pdf_bytes, filetype="pdf")

for page_index in range(len(doc)):
    page = doc[page_index]
    image_list = page.get_images(full=True)

    for img_index, img in enumerate(image_list):
        xref = img[0]
        pix = fitz.Pixmap(doc, xref)

        if pix.alpha:  # handle alpha channel
            pix = fitz.Pixmap(fitz.csRGB, pix)

        pix.save(f"page{page_index}_img{img_index}.png")

AttributeError: module 'fitz' has no attribute 'open'

In [13]:
!pip uninstall -y fitz

Found existing installation: fitz 0.0.1.dev2
Uninstalling fitz-0.0.1.dev2:
  Successfully uninstalled fitz-0.0.1.dev2

In [14]:
!pip install --upgrade PyMuPDF

Requirement already satisfied: PyMuPDF in /usr/local/lib/python3.12/dist-packages (1.26.6)

In [18]:
import sys
if 'fitz' in sys.modules:
    del sys.modules['fitz']

import fitz  # PyMuPDF
import io

doc = fitz.open(stream=pdf_bytes, filetype="pdf")

for page_index in range(len(doc)):
    page = doc[page_index]
    image_list = page.get_images(full=True)

    for img_index, img in enumerate(image_list):
        xref = img[0]
        pix = fitz.Pixmap(doc, xref)

        if pix.alpha:  # handle alpha channel
            pix = fitz.Pixmap(fitz.csRGB, pix)

        pix.save(f"page{page_index}_img{img_index}.png")

AttributeError: module 'fitz' has no attribute 'open'

In [ ]:
blob_client=blob_service_client_using_connection_string \
            .get_blob_client("vgpcontainer","Visadataset.csv")

data=blob_client.download_blob()
# we will write the data of bank.csv in another files

import pandas as pd
pd.read_csv(data)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [ ]:
import pandas as pd
pd.read_csv(data)

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0     30;"unemployed";"married";"primary";"no";1787;...
1     33;"services";"married";"secondary";"no";4789;...
2     35;"management";"single";"tertiary";"no";1350;...
3     30;"management";"married";"tertiary";"no";1476...
4     59;"blue-collar";"married";"secondary";"no";0;...
...                                                 ...
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

[4521 rows x 1 columns]

In [ ]:
from azure.storage.blob import BlobServiceClient
blob_account_url="https://storageforde.blob.core.windows.net/"
storage_credential="MfHfi/aTTNq/jNoyz31qA89Hy7c4N24TspPqeML99eyPS9mhOsQ6cOH0hUhbmReeg3TFGfx7CdjH+AStMYaESQ=="
blob_service_client=BlobServiceClient(account_url=blob_account_url,
                                      credential=storage_credential)

blob_client=blob_service_client \
            .get_blob_client("pythonnareshit1","bank.csv")

data=blob_client.download_blob()
# we will write the data of bank.csv in another files

import pandas as pd
pd.read_csv(data,sep=';')

#=============================================================================
from azure.storage.blob import BlobServiceClient
connection_string='DefaultEndpointsProtocol=https;AccountName=storageforde;AccountKey=MfHfi/aTTNq/jNoyz31qA89Hy7c4N24TspPqeML99eyPS9mhOsQ6cOH0hUhbmReeg3TFGfx7CdjH+AStMYaESQ==;EndpointSuffix=core.windows.net'
blob_service_client_using_connection_string=BlobServiceClient.from_connection_string(connection_string)


blob_client=blob_service_client_using_connection_string \
            .get_blob_client("pythonnareshit1","bank.csv")

data=blob_client.download_blob()
# we will write the data of bank.csv in another files

import pandas as pd
pd.read_csv(data,sep=';')